'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,ArrowUpRight,Database,RefreshCw,Target,TrendingUp,X,Zap} from 'lucide-react'
export default function Problems(){
 const [data,setData]=useState<any>({}),[busy,setBusy]=useState(true),[ingest,setIngest]=useState(false),[selected,setSelected]=useState<any>(null),[filter,setFilter]=useState('all')
 const load=async()=>{setBusy(true);try{const r=await fetch('/api/problems?limit=100',{cache:'no-store'});setData(await r.json())}catch(e){setData({ok:false,error:String(e)})}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const run=async()=>{setIngest(true);try{const r=await fetch('/api/signals/ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:100})});const j=await r.json();setData((x:any)=>({...x,ingest:j.result||j}));await load()}finally{setIngest(false)}}
 const clusters=useMemo(()=>((data.clusters||[]) as any[]).filter(c=>filter==='all'||(filter==='emerging'?c.status==='emerging':filter==='high'?Number(c.momentum_score)>=50:true)),[data,filter])
 const signals=(data.signals||[]) as any[]
 return <div className='phase3-shell'>
  <div className='phase3-top'><div><div className='eyebrow'>VENTUREOS / PHASE 3</div><h1>Problem Atlas</h1><p>Turn raw web intelligence into structured, traceable market problems.</p></div><div className='phase3-actions'><button className='p3-btn' onClick={load}><RefreshCw size={14}/> Refresh</button><button className='p3-primary' onClick={run} disabled={ingest}><Zap size={14}/>{ingest?'Processing signal engine…':'Process research → problems'}</button></div></div>
  <section className='p3-metrics'><div className='p3-stat'><span>ACTIVE SIGNALS</span><b>{signals.length.toLocaleString()}</b><small>normalized + classified</small></div><div className='p3-stat'><span>PROBLEM CLUSTERS</span><b>{clusters.length}</b><small>deduplicated themes</small></div><div className='p3-stat'><span>EMERGING</span><b>{clusters.filter((x:any)=>x.status==='emerging').length}</b><small>≥ 3 supporting signals</small></div><div className='p3-stat'><span>HIGH MOMENTUM</span><b>{clusters.filter((x:any)=>Number(x.momentum_score)>=50).length}</b><small>7d vs previous 7d</small></div></section>
  {!data.ok&&!busy&&<div className='p3-alert'><AlertTriangle size={15}/><div><b>Signal engine is not connected yet.</b><span>{data.error||'Configure the server-side Supabase credentials, then run ingestion.'}</span></div></div>}
  <section className='p3-layout'><div className='p3-main'>
   <div className='p3-panel'><div className='p3-head'><div><b>Problem universe</b><span>Clusters ranked by current momentum</span></div><div className='p3-filters'>{['all','emerging','high'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{busy?<div className='p3-empty'><RefreshCw className='spin' size={18}/><b>Loading problem graph…</b></div>:clusters.length===0?<div className='p3-empty'><Target size={22}/><b>No problem clusters yet</b><span>Run Signal Engine after Phase 2 has stored research sources.</span></div>:<div className='p3-clusters'>{clusters.map((c:any,i:number)=><button className='p3-cluster' key={c.id} onClick={()=>setSelected(c)}><div className='p3-cluster-index'>{String(i+1).padStart(2,'0')}</div><div className='p3-cluster-body'><div className='p3-cluster-title'><b>{c.name}</b><span>{c.status}</span></div><p>{c.description}</p><div className='p3-bars'><div><label>Signals</label><strong>{c.signal_count}</strong></div><div><label>Momentum</label><strong className={Number(c.momentum_score)>=50?'up':''}>{Number(c.momentum_score)>0?'+':''}{c.momentum_score}%</strong></div><div><label>Pain</label><strong>{c.pain_score}</strong></div><div><label>Demand</label><strong>{c.demand_score}</strong></div></div></div><ArrowUpRight size={15}/></button>)}</div>}</div>
   <div className='p3-panel'><div className='p3-head'><div><b>Recent normalized signals</b><span>Classification and entity resolution output</span></div><Database size={15}/></div><div className='p3-signal-table'>{signals.slice(0,18).map((s:any)=><div className='p3-signal' key={s.id}><div className='p3-signal-dot'/><div><b>{s.title}</b><span>{s.signal_type} · {s.industry||'General'} · {s.entity_domain||'unresolved entity'}</span></div><strong>{Math.round(Number(s.classification_confidence||0))}%</strong></div>)}</div></div>
  </div><aside className='p3-side'><div className='p3-panel'><div className='p3-head'><div><b>Engine pipeline</b><span>Phase 3 processing state</span></div><TrendingUp size={15}/></div><div className='p3-pipeline'>{['Normalize raw sources','Deduplicate content','Classify signal type','Resolve entities','Create embeddings*','Cluster recurring problems','Detect momentum'].map((x,i)=><div className='p3-step' key={x}><i>{String(i+1).padStart(2,'0')}</i><span>{x}</span><b>{i<4?'ready':i===4?'optional':'ready'}</b></div>)}</div><p className='p3-footnote'>* Embeddings use OpenAI <code>text-embedding-3-small</code> when <code>OPENAI_API_KEY</code> is configured; the rest of the Phase 3 pipeline does not depend on embeddings.</p></div><div className='p3-panel p3-contract'><div className='p3-head'><div><b>Traceability contract</b><span>Every problem must stay explainable</span></div></div><div className='p3-contract-row'><span>Observed source</span><b>URL + snippet</b></div><div className='p3-contract-row'><span>Signal</span><b>normalized record</b></div><div className='p3-contract-row'><span>Cluster</span><b>problem theme</b></div><div className='p3-contract-row'><span>Momentum</span><b>7d comparison</b></div></div></aside></section>
 {selected&&<div className='overlay' onClick={()=>setSelected(null)}><aside className='drawer p3-drawer' onClick={(e:any)=>e.stopPropagation()}><div className='drawerhead'><div><div className='eyebrow'>PROBLEM CLUSTER</div><h2>{selected.name}</h2></div><button className='icon' onClick={()=>setSelected(null)}><X size={15}/></button></div><p className='drawerintro'>{selected.description}</p><div className='p3-detail-grid'><div><span>Signals</span><b>{selected.signal_count}</b></div><div><span>Evidence</span><b>{selected.evidence_count}</b></div><div><span>Momentum</span><b>{selected.momentum_score}%</b></div><div><span>Confidence</span><b>{selected.confidence}%</b></div></div><div className='p3-detail-section'><label>Industries</label><div>{(selected.industries||[]).map((x:string)=><span key={x}>{x}</span>)}</div></div><div className='p3-detail-section'><label>Audiences</label><div>{(selected.audiences||[]).map((x:string)=><span key={x}>{x}</span>)}</div></div><button className='p3-primary wide' onClick={async()=>{const r=await fetch('/api/problems?cluster='+selected.id);const j=await r.json();setSelected({...selected,signals:j.signals||[]})}}><Database size={14}/> Load supporting signals</button>{Array.isArray(selected.signals)&&<div className='p3-support'>{selected.signals.slice(0,20).map((m:any)=><article key={m.signal?.id||m.signal_id}><b>{m.signal?.title||'Signal'}</b><p>{m.signal?.normalized_text?.slice(0,280)}</p><a href={m.signal?.source_url} target='_blank' rel='noreferrer'>Open source ↗</a></article>)}</div>}</aside></div>}
 </div>
}