import { ventureosConfigured, ventureosRequest } from '@/lib/tenant/rest'
const request = ventureosRequest
export const configured=()=>ventureosConfigured()
export async function getProfile(founderKey='primary'){const rows=await request('ventureos_founder_profiles?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&limit=1');return rows?.[0]??null}
export async function upsertProfile(row:Record<string,unknown>){const key=String(row.founder_key||'primary');const existing=await getProfile(key);if(existing){const [r]=await request('ventureos_founder_profiles?id=eq.'+existing.id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return r}return(await request('ventureos_founder_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,founder_key:key})}))[0]}
export async function listPreferences(founderKey='primary'){return request('ventureos_founder_preferences?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&status=eq.active&order=weight.desc,confidence.desc&limit=100')}
export async function upsertPreference(row:Record<string,unknown>){const q='founder_key=eq.'+encodeURIComponent(String(row.founder_key||'primary'))+'&category=eq.'+encodeURIComponent(String(row.category))+'&preference_key=eq.'+encodeURIComponent(String(row.preference_key));const existing=await request('ventureos_founder_preferences?select=*&'+q+'&limit=1');if(existing?.[0]){const [r]=await request('ventureos_founder_preferences?id=eq.'+existing[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return r}return(await request('ventureos_founder_preferences',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function listDecisions(founderKey='primary',limit=100){return request('ventureos_founder_decisions?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&order=decided_at.desc&limit='+Math.min(limit,200))}
export async function addDecision(row:Record<string,unknown>){return(await request('ventureos_founder_decisions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function listLessons(founderKey='primary',limit=100){return request('ventureos_founder_lessons?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&status=eq.active&order=learned_at.desc&limit='+Math.min(limit,200))}
export async function addLesson(row:Record<string,unknown>){return(await request('ventureos_founder_lessons',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function listMemory(founderKey='primary',limit=100){return request('ventureos_founder_memory?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&order=importance.desc,updated_at.desc&limit='+Math.min(limit,200))}
export async function addMemory(row:Record<string,unknown>){return(await request('ventureos_founder_memory',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function getSnapshot(founderKey='primary',date?:string){const d=date||new Date().toISOString().slice(0,10);const rows=await request('ventureos_daily_snapshots?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&snapshot_date=eq.'+encodeURIComponent(d)+'&limit=1');return rows?.[0]??null}
export async function listSnapshots(founderKey='primary',limit=30){return request('ventureos_daily_snapshots?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&order=snapshot_date.desc&limit='+Math.min(limit,100))}
export async function listSnapshotItems(snapshotId:number,limit=100){return request('ventureos_daily_snapshot_items?select=*&snapshot_id=eq.'+snapshotId+'&order=change_score.desc,created_at.desc&limit='+Math.min(limit,200))}
export async function upsertSnapshot(row:Record<string,unknown>){const key='founder_key=eq.'+encodeURIComponent(String(row.founder_key||'primary'))+'&snapshot_date=eq.'+encodeURIComponent(String(row.snapshot_date));const existing=await request('ventureos_daily_snapshots?select=*&'+key+'&limit=1');if(existing?.[0]){const [r]=await request('ventureos_daily_snapshots?id=eq.'+existing[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return r}return(await request('ventureos_daily_snapshots',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function replaceSnapshotItems(snapshotId:number,items:Record<string,unknown>[]){await request('ventureos_daily_snapshot_items?snapshot_id=eq.'+snapshotId,{method:'DELETE'});if(items.length)await request('ventureos_daily_snapshot_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(items.map(x=>({...x,snapshot_id:snapshotId})))});}
export async function createDailyRun(row:Record<string,unknown>){return(await request('ventureos_daily_processing_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function finishDailyRun(id:string,patch:Record<string,unknown>){await request('ventureos_daily_processing_runs?run_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...patch,completed_at:new Date().toISOString(),status:patch.error?'partial':'completed'})})}
export async function getDailyRuns(founderKey='primary',limit=20){return request('ventureos_daily_processing_runs?select=*&founder_key=eq.'+encodeURIComponent(founderKey)+'&order=started_at.desc&limit='+Math.min(limit,50))}
export async function sourceRows(){const [events,problems,opportunities]=await Promise.all([request('ventureos_market_events?select=*&order=detected_at.desc&limit=20'),request('ventureos_problem_clusters?select=*&status=neq.archived&order=momentum_score.desc&limit=20'),request('ventureos_opportunities?select=*&order=overall_score.desc&limit=20')]);return{events,problems,opportunities}}
