'use client'
import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,BarChart3,Database,RefreshCw,Search,TrendingUp,X} from 'lucide-react'
export default function Market(){
 const [data,setData]=useState<any>({}),[busy,setBusy]=useState(true),[processing,setProcessing]=useState(false),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<any>(null)
 const load=async()=>{setBusy(true);try{const r=await fetch('/api/market',{cache:'no-store'});setData(await r.json())}catch(e){setData({ok:false,error:String(e)})}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const process=async()=>{setProcessing(true);try{await fetch('/api/market/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:1000})});await load()}finally{setProcessing(false)}}
 const trends=useMemo(()=>((data.trends||[]) as any[]).filter(x=>filter==='all'||(filter==='rising'?Number(x.momentum_score)>0:filter==='high'?Number(x.confidence)>=80:true)),[data,filter])
 return <div className='phase4-shell'>
 <div className='phase4-top'><div><div className='eyebrow'>VENTUREOS / PHASE 4</div><h1>Market Pulse</h1><p>Evidence-backed market changes, trends and competitor movement.</p></div><div className='phase4-actions'><button className='p4-btn' onClick={load}><RefreshCw size={14}/> Refresh</button><button className='p4-primary' disabled={processing} onClick={process}>{processing?<><RefreshCw className='spin' size={14}/> Rebuilding intelligence…</>:<><TrendingUp size={14}/> Process evidence + market intelligence</>}</button></div></div>
 <section className='p4-kpis'><div><span>MARKET EVENTS</span><b>{data.events?.length||0}</b><small>detected changes</small></div><div><span>TRENDS</span><b>{data.trends?.length||0}</b><small>tracked patterns</small></div><div><span>EVIDENCE</span><b>{data.evidence?.length||0}</b><small>ranked claims</small></div><div><span>COMPETITORS</span><b>{data.competitors?.length||0}</b><small>observed entities</small></div></section>
 {!data.configured&&<div className='p4-alert'><AlertTriangle size={15}/><div><b>Market data is in configuration mode.</b><span>{data.message||'Connect the server-side Supabase credentials to load live evidence and trends.'}</span></div></div>}
 <section className='p4-grid'><div className='p4-main'>
 <div className='p4-panel'><div className='p4-head'><div><b>Market changes</b><span>Detected events with confidence and impact</span></div><Activity size={15}/></div><div className='p4-events'>{(data.events||[]).slice(0,12).map((e:any)=><button className='p4-event' key={e.id} onClick={()=>setSelected(e)}><div className='p4-event-meta'><span>{e.event_type}</span><em>{e.detected_at?new Date(e.detected_at).toLocaleDateString('en-IN'):''}</em></div><b>{e.title}</b><p>{e.description}</p><div className='p4-event-stats'><span>Impact <strong>{e.impact_score}</strong></span><span>Momentum <strong>{e.momentum_score>0?'+':''}{e.momentum_score}%</strong></span><span>Evidence <strong>{e.source_count}</strong></span><span>Confidence <strong>{e.confidence}%</strong></span></div></button>)}</div>{!(data.events||[]).length&&!busy&&<div className='p4-empty'><Activity size={21}/><b>No market changes yet</b><span>Run the Phase 4 processing pass after research signals exist.</span></div>}</div>
 <div className='p4-panel'><div className='p4-head'><div><b>Trend intelligence</b><span>Current 7d window versus previous 7d</span></div><div className='p4-filters'>{['all','rising','high'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className='p4-trends'>{trends.slice(0,16).map((t:any)=><div className='p4-trend' key={t.id}><div><b>{t.label}</b><span>{t.description}</span></div><div className='p4-trend-right'><strong className={Number(t.momentum_score)>=0?'up':'down'}>{Number(t.momentum_score)>0?'+':''}{t.momentum_score}%</strong><small>{t.signal_count} signals · {t.unique_sources} sources</small></div></div>)}</div></div>
 </div><aside className='p4-side'>
 <div className='p4-panel'><div className='p4-head'><div><b>Competitor snapshots</b><span>Observed changes by entity</span></div><BarChart3 size={15}/></div><div className='p4-competitors'>{(data.competitors||[]).slice(0,10).map((c:any)=><div className='p4-comp' key={c.id}><div className='p4-comp-top'><b>{c.entity_name}</b><strong className={Number(c.change_score)>=0?'up':'down'}>{Number(c.change_score)>0?'+':''}{c.change_score}%</strong></div><span>{c.entity_domain} · {c.source_count} sources</span><div className='p4-tags'>{(c.pricing_signals||[]).slice(0,2).map((x:string)=><i key={x}>pricing</i>)}{(c.product_signals||[]).slice(0,2).map((x:string)=><i key={x}>product</i>)}</div></div>)}</div></div>
 <div className='p4-panel p4-evidence-mini'><div className='p4-head'><div><b>Evidence quality</b><span>Top ranked supporting claims</span></div><Database size={15}/></div>{(data.evidence||[]).slice(0,8).map((e:any)=><button key={e.id} onClick={()=>setSelected(e)}><span>{e.evidence_status}</span><b>{e.claim_text}</b><small>{e.source_domain} · {e.evidence_score}/100</small></button>)}</div>
 </aside></section>
 {selected&&<div className='overlay' onClick={()=>setSelected(null)}><aside className='drawer p4-drawer' onClick={(e:any)=>e.stopPropagation()}><div className='drawerhead'><div><div className='eyebrow'>{selected.event_type?'MARKET EVENT':'EVIDENCE'}</div><h2>{selected.title||selected.claim_text}</h2></div><button className='icon' onClick={()=>setSelected(null)}><X size={15}/></button></div><p className='drawerintro'>{selected.description||selected.snippet||'Evidence-backed intelligence record.'}</p><div className='p3-detail-grid'><div><span>Confidence</span><b>{selected.confidence??Math.round(Number(selected.source_confidence||0)*100)}%</b></div><div><span>Evidence</span><b>{selected.source_count??selected.evidence_score??0}</b></div><div><span>Impact</span><b>{selected.impact_score??'—'}</b></div><div><span>Momentum</span><b>{selected.momentum_score??'—'}{selected.momentum_score!=null?'%':''}</b></div></div>{selected.source_url&&<div className='p3-detail-section'><label>Source</label><a className='p4-source-link' href={selected.source_url} target='_blank' rel='noreferrer'>{selected.source_domain||selected.source_url} ↗</a><p className='p4-quote'>{selected.snippet||selected.claim_text}</p></div>}</aside></div>}
 </div>
}