import {canTransition,configured,insertHistory,latestMetric,lifecycleHistory,metrics,patchProduct,portfolioProduct,portfolioProducts,productCounts,type Lifecycle,upsertMetric} from './storage'
const progressByStatus:Record<string,number>={ideas:0,validation:18,mvp:40,building:68,beta:84,live:100,paused:70,archived:100,killed:0}
const phaseByStatus:Record<string,string>={ideas:'Research',validation:'Validation',mvp:'MVP',building:'Development',beta:'Beta',live:'Live',paused:'Paused',archived:'Archived',killed:'Killed'}
export async function portfolio(){if(!configured())return{configured:false,products:[],counts:null};const x=await productCounts();return{configured:true,...x}}
export async function portfolioDetail(id:number){if(!configured())return{configured:false,product:null,history:[],metrics:[]};const product=await portfolioProduct(id);if(!product)return null;const [history,metricRows]=await Promise.all([lifecycleHistory(id),metrics(id)]);return{configured:true,product,history,metrics:metricRows}}
export async function transitionProduct(id:number,toStatus:Lifecycle,reason='',changedBy='founder'){if(!configured())throw new Error('Supabase server credentials are not configured');const product=await portfolioProduct(id);if(!product)throw new Error('Product not found');const from=String(product.status||'ideas');if(!canTransition(from,toStatus))throw new Error('Invalid lifecycle transition: '+from+' → '+toStatus);if(from===toStatus)return portfolioDetail(id);const patch={status:toStatus,current_phase:phaseByStatus[toStatus],progress:progressByStatus[toStatus],last_transition_at:new Date().toISOString()};const updated=await patchProduct(id,patch);await insertHistory({product_id:id,from_status:from,to_status:toStatus,reason:reason||null,changed_by:changedBy,metadata:{source:'portfolio_state_machine'}});return portfolioDetail(id)
}
export async function recordProductMetric(id:number,input:any){if(!configured())throw new Error('Supabase server credentials are not configured');const date=String(input.metric_date||new Date().toISOString().slice(0,10));const row={product_id:id,metric_date:date,customer_count:Number(input.customer_count||0),mrr:Number(input.mrr||0),api_cost:Number(input.api_cost||0),gross_margin:Number(input.gross_margin||0),activation_rate:Number(input.activation_rate||0),retention_rate:Number(input.retention_rate||0),metadata:input.metadata||{}};await upsertMetric(row);return latestMetric(id)}
export function allowedNextStatuses(status:string){const map:any={ideas:['validation','killed','archived'],validation:['mvp','ideas','killed','archived'],mvp:['building','validation','killed','archived'],building:['beta','mvp','paused','killed'],beta:['live','building','paused','killed'],live:['paused','archived'],paused:['building','beta','live','archived','killed'],archived:['ideas'],killed:['ideas']};return map[status]||[]}
