

import crypto from 'node:crypto'
import {artifactList,configured,createArtifacts,createFeatures,createProduct,createRun,featureList,finishRun,opportunityById,productByOpportunity,productById,listProducts,updateProduct} from './storage'
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex').slice(0,12)}
function clean(v:any,fallback=''){const s=String(v??'').trim();return s||fallback}
function makeName(o:any){return clean(o.title,'Opportunity Product').replace(/\s+/g,' ').slice(0,72)}
function moneyBand(score:number){return score>=80?'Premium B2B SaaS subscription':score>=60?'Core B2B SaaS subscription':'Pilot + usage-based plan'}
function feature(title:string,description:string,priority:string,phase:string,dependencies:string[]=[],criteria:string[]=[]){return{feature_key:hash(title),title,description,priority,phase,status:'planned',dependencies,acceptance_criteria:criteria}}
export function buildProductSpec(o:any){
 const name=makeName(o),audience=clean(o.target_audience,'Focused B2B teams'),problem=clean(o.summary,'Recurring workflow problem'),business=clean(o.business_model,'B2B SaaS'),pricing=moneyBand(Number(o.monetization_score||0));
 const features=[feature('Workspace onboarding','Capture minimum customer context for the core workflow.','P0','MVP',[],['User can complete onboarding.','Configuration persists.']),feature('Core workflow engine','Automate the primary job represented by the opportunity.','P0','MVP',['Workspace onboarding'],['A representative task completes end-to-end.','Errors are recoverable.']),feature('Evidence and activity trail','Expose actions, reasons and traceable inputs.','P0','MVP',['Core workflow engine'],['Every meaningful action is auditable.']),feature('Human review queue','Approve, reject or edit high-impact outputs.','P1','MVP',['Core workflow engine'],['Review state transitions are deterministic.']),feature('Usage and outcome analytics','Track usage, quality and business outcomes.','P1','Post-MVP',['Core workflow engine'],['Core funnel events are recorded.']),feature('Integrations layer','Connect the minimum external systems required by the workflow.','P1','Post-MVP',['Core workflow engine'],['Integration health is visible.'])];
 const thesis='Build a focused '+business+' product for '+audience+', starting from the observed problem: '+problem;
 const prd={summary:thesis,problem_statement:problem,target_customer:audience,goals:['Reduce the friction represented by the source problem.','Deliver a measurable outcome for the first customer segment.','Validate repeatable value before broad expansion.'],non_goals:['Broad platform before the core workflow is proven.','Uncontrolled autonomous execution.','Large integration catalog before validation.'],user_stories:['Configure the workflow without engineering help.','See progress and evidence for each run.','Review or override important outputs.','Measure outcomes before scaling.']};
 const schema={tables:[{name:'workspaces',purpose:'Tenant boundary',fields:['id','name','owner_id','status']},{name:'workflow_runs',purpose:'Execution state',fields:['id','workspace_id','input','status','started_at','completed_at']},{name:'workflow_items',purpose:'User-visible work',fields:['id','run_id','type','status','input','output','confidence']},{name:'evidence_links',purpose:'Traceability',fields:['id','workflow_item_id','source_type','source_ref','claim','confidence']},{name:'usage_events',purpose:'Usage and metering',fields:['id','workspace_id','event','quantity','cost_units']} ]};
 const api={endpoints:[{method:'POST',path:'/api/product/workflows',purpose:'Create workflow run'},{method:'GET',path:'/api/product/workflows/:id',purpose:'Read workflow state'},{method:'POST',path:'/api/product/workflows/:id/review',purpose:'Review output'},{method:'GET',path:'/api/product/usage',purpose:'Read product usage'},{method:'GET',path:'/api/product/evidence/:id',purpose:'Read supporting evidence'}]};
 const mvp={milestones:[{name:'Research lock',exit:'Problem, audience and evidence confirmed.'},{name:'PRD + UX',exit:'User journey and acceptance criteria frozen.'},{name:'Architecture',exit:'Schema, APIs, security and observability defined.'},{name:'Core build',exit:'P0 workflow works end-to-end.'},{name:'Pilot',exit:'Real user completes workflow and outcome is measured.'},{name:'Launch gate',exit:'Reliability, analytics, pricing and support ready.'}]};
 const ux={sitemap:['Overview','Onboarding','Core Workflow','Review Queue','Evidence / Activity','Usage & Outcomes','Settings'],primary_flow:'Onboarding -> Configure -> Run -> Review -> Approve/Correct -> Outcome -> History'};
 const architecture={frontend:'Next.js app',backend:'API + async workflow worker',data:'Supabase/Postgres with RLS',integrations:['Provider adapters','Webhook boundary','Server-side secret storage'],observability:['Structured logs','Run IDs','Usage events','Error states'],security:['Authentication','RLS','Rate limiting','Idempotency']};
 const analytics={events:['workspace_created','workflow_started','workflow_completed','review_approved','review_rejected','outcome_recorded','integration_connected']};
 const economics={pricing_hypothesis:pricing,monetization_score:Number(o.monetization_score||0),build_complexity_score:Number(o.build_complexity_score||0),cost_controls:['Per-run metering','Daily/monthly guardrails','Provider routing by capability, quality, latency and cost']};
 const validation={gates:['Validate with 5–10 direct user conversations.','Run a concierge or pilot workflow before full automation.','Measure time saved, completion rate, rejection rate and willingness to pay.','Stop or revise if repeatable value is not supported.']};
 const pricingHypothesis={hypothesis:pricing,signals:{monetization_score:Number(o.monetization_score||0),business_model:business}};
 const artifacts=[['prd','Product Requirements Document',prd],['feature_map','Feature Map',{features}],['ux_map','UX Map',ux],['architecture','Architecture',architecture],['schema','Database Schema',schema],['api_spec','API Specification',api],['mvp_plan','MVP Plan',mvp],['analytics_plan','Analytics Plan',analytics],['economics','Economics & Pricing',economics],['validation_plan','Validation Plan',validation],['pricing_hypothesis','Pricing Hypothesis',pricingHypothesis]];
 return{name,thesis,problem_statement:problem,target_customer:audience,positioning:'Evidence-backed '+name+' focused on one measurable workflow outcome before platform expansion.',business_model:business,pricing_hypothesis:pricingHypothesis.hypothesis,validation_plan:validation.gates,mvp_plan:mvp,economics,architecture,analytics_plan:analytics,features,artifacts}
}
export async function generateProductFromOpportunity(opportunityId:number,founderKey='primary'){if(!configured())throw new Error('Supabase server credentials are not configured');const runId='product_'+Date.now().toString(36),o=await opportunityById(opportunityId);if(!o)throw new Error('Opportunity not found');await createRun({run_id:runId,opportunity_id:opportunityId,status:'running',metadata:{engine:'product_architect_v1'}});try{const existing=await productByOpportunity(opportunityId),spec=buildProductSpec(o);const product=existing?await updateProduct(Number(existing.id),{name:spec.name,thesis:spec.thesis,target_customer:spec.target_customer,problem_statement:spec.problem_statement,positioning:spec.positioning,business_model:spec.business_model,pricing_hypothesis:spec.pricing_hypothesis,validation_plan:spec.validation_plan,mvp_plan:spec.mvp_plan,economics:spec.economics,architecture:spec.architecture,analytics_plan:spec.analytics_plan,status:existing.status||'ideas',metadata:{opportunity_id:opportunityId,generated_at:new Date().toISOString()}}):await createProduct({product_key:'prod_'+hash(String(opportunityId)+'|'+spec.name),opportunity_id:opportunityId,founder_key:founderKey,name:spec.name,status:'ideas',thesis:spec.thesis,target_customer:spec.target_customer,problem_statement:spec.problem_statement,positioning:spec.positioning,business_model:spec.business_model,pricing_hypothesis:spec.pricing_hypothesis,validation_plan:spec.validation_plan,mvp_plan:spec.mvp_plan,economics:spec.economics,architecture:spec.architecture,analytics_plan:spec.analytics_plan,metadata:{opportunity_title:o.title,opportunity_score:o.overall_score,generated_at:new Date().toISOString()}});const artifactRows=spec.artifacts.map((row:any)=>({product_id:product.id,artifact_type:row[0],title:row[1],version:1,content:row[2],status:'generated',generated_by:'product_architect'}));await createArtifacts(artifactRows);await createFeatures(spec.features.map((f:any)=>({...f,product_id:product.id})));await finishRun(runId,{product_id:product.id,artifacts_created:artifactRows.length,features_created:spec.features.length});return{product,artifacts:await artifactList(product.id),features:await featureList(product.id),runId}}catch(e){await finishRun(runId,{error:e instanceof Error?e.message:String(e)});throw e}}
export async function productDetail(id:number){const product=await productById(id);if(!product)return null;return{product,artifacts:await artifactList(id),features:await featureList(id)}}
export async function products(){return listProducts(100)}

