import crypto from 'node:crypto'
import { artifacts, configured, createArtifacts, createRun, createSteps, latestRun, patchProduct, product, runByKey, runs, step, steps, updateRun, updateStep } from './storage'
import { figmaValidate, githubProvision, providerHealth, vercelDeploy, vercelStatus } from './providers'

const STEP_DEFS = [
  { key: 'spec_validation', provider: 'ventureos' },
  { key: 'build_agent_scaffold', provider: 'build_agent' },
  { key: 'github_provision', provider: 'github' },
  { key: 'figma_handoff', provider: 'figma' },
  { key: 'supabase_schema', provider: 'supabase' },
  { key: 'vercel_deploy', provider: 'vercel' },
  { key: 'build_verification', provider: 'vercel' }
]

function hash(v: string) {
  return crypto.createHash('sha256').update(v).digest('hex').slice(0, 16)
}

function jsonText(v: unknown) {
  return typeof v === 'string' ? v : JSON.stringify(v, null, 2)
}

async function productArtifacts(productId: number) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY
  if (!url || !key) throw new Error('Supabase server credentials are not configured')
  const api = url.replace(/\/$/, '') + '/rest/v1/ventureos_product_artifacts?select=*&product_id=eq.' + productId + '&order=artifact_type.asc,version.desc'
  const r = await fetch(api, { headers: { apikey: key, Authorization: 'Bearer ' + key }, cache: 'no-store' })
  if (!r.ok) throw new Error('Product artifact read failed: ' + r.status)
  return r.json()
}

async function productFeatures(productId: number) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY
  if (!url || !key) throw new Error('Supabase server credentials are not configured')
  const api = url.replace(/\/$/, '') + '/rest/v1/ventureos_product_features?select=*&product_id=eq.' + productId + '&order=phase.asc,priority.asc'
  const r = await fetch(api, { headers: { apikey: key, Authorization: 'Bearer ' + key }, cache: 'no-store' })
  if (!r.ok) throw new Error('Product feature read failed: ' + r.status)
  return r.json()
}

function buildFiles(product: any, factoryArtifacts: any[], features: any[]) {
  function artifact(type: string) {
    for (const row of factoryArtifacts) if (row.artifact_type === type) return row.content
    return {}
  }
  const featureText = features.map(function (f: any) {
    return '- [ ] ' + f.priority + ': ' + f.title + ' — ' + f.description
  }).join('\n')

  const packageJson = {
    name: 'ventureos-' + product.id + '-product',
    private: true,
    version: '0.1.0',
    scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    dependencies: { next: 'latest', react: 'latest', 'react-dom': 'latest' },
    devDependencies: { typescript: 'latest', '@types/node': 'latest', '@types/react': 'latest', '@types/react-dom': 'latest' }
  }

  const generatedFeatures = JSON.stringify(features.map(function (f: any) {
    return { key: f.feature_key, title: f.title, description: f.description, priority: f.priority }
  }))
  const pageSource = "const features = " + generatedFeatures + ";\n\nexport default function Home(){return <main className=\"shell\"><header><span>VENTURE PRODUCT / GENERATED BY VENTUREOS</span><h1>" + product.name + "</h1><p>" + product.thesis + "</p></header><section><h2>Built for</h2><p>" + product.target_customer + "</p></section><section><h2>MVP feature map</h2><ul>{features.map(function(feature){return <li key={feature.key}><strong>{feature.title}</strong><span>{feature.description}</span></li>})}</ul></section><footer><span>Execution scaffold generated by VentureOS.</span><span>Build-ready baseline · review before production launch.</span></footer></main>}"
  const layoutSource = "import './globals.css'\n\nexport const metadata = { title: " + JSON.stringify(product.name) + ", description: " + JSON.stringify(product.thesis) + " }\n\nexport default function RootLayout({children}:{children:React.ReactNode}){return <html lang=\"en\"><body>{children}</body></html>}"
  const cssSource = ":root{color-scheme:dark}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#07090d;color:#eef3f7;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}body{padding:0}.shell{max-width:1080px;margin:0 auto;padding:80px 28px 56px}.shell header{padding-bottom:42px;border-bottom:1px solid rgba(255,255,255,.1)}.shell header span,.shell footer span:first-child{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#83a0b6}.shell h1{font-size:clamp(46px,8vw,88px);line-height:.95;letter-spacing:-.05em;max-width:900px;margin:20px 0}.shell p{font-size:18px;line-height:1.7;color:#aebcc8;max-width:760px}.shell section{padding:40px 0;border-bottom:1px solid rgba(255,255,255,.08)}.shell h2{font-size:14px;letter-spacing:.12em;text-transform:uppercase;color:#7fd7ef}.shell ul{list-style:none;padding:0;margin:22px 0;display:grid;gap:12px}.shell li{display:grid;gap:8px;padding:20px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025);border-radius:18px}.shell li span{color:#91a0ad;line-height:1.6}.shell footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;padding-top:28px;color:#7d8a95;font-size:12px}"
  return [
    { path: 'README.md', content: '# ' + product.name + '\n\nGenerated by VentureOS Phase 10 Execution Layer.\n\n## Thesis\n' + product.thesis + '\n\n## Target customer\n' + product.target_customer + '\n' },
    { path: 'app/layout.tsx', content: layoutSource },
    { path: 'app/page.tsx', content: pageSource },
    { path: 'app/globals.css', content: cssSource },
    { path: 'tsconfig.json', content: JSON.stringify({ compilerOptions: { target: 'ES2017', lib: ['dom', 'dom.iterable', 'esnext'], allowJs: false, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: 'esnext', moduleResolution: 'bundler', resolveJsonModule: true, isolatedModules: true, jsx: 'preserve', incremental: true, plugins: [{ name: 'next' }] }, include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'], exclude: ['node_modules'] }, null, 2) },
    { path: 'next-env.d.ts', content: '/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file should not be edited.' },
    { path: 'next.config.js', content: '/** @type {import(\"next\").NextConfig} */\nmodule.exports = { reactStrictMode: true }' },
    { path: 'docs/PRD.md', content: jsonText(artifact('prd')) },
    { path: 'docs/UX.md', content: jsonText(artifact('ux_map')) },
    { path: 'docs/ARCHITECTURE.md', content: jsonText(artifact('architecture')) },
    { path: 'docs/API.md', content: jsonText(artifact('api_spec')) },
    { path: 'docs/MVP.md', content: jsonText(artifact('mvp_plan')) },
    { path: 'docs/FEATURES.md', content: featureText || 'No features generated.' },
    { path: 'supabase/schema.json', content: jsonText(artifact('schema')) },
    { path: 'supabase/README.md', content: 'Review the generated schema before applying it to the target Supabase project.' },
    { path: 'design/figma-handoff.json', content: JSON.stringify({ product: product.name, ux: artifact('ux_map'), source: 'VentureOS' }, null, 2) },
    { path: 'execution/build-manifest.json', content: JSON.stringify({ product_id: product.id, product_name: product.name, steps: STEP_DEFS.map(function (s) { return s.key }) }, null, 2) },
    { path: 'package.json', content: JSON.stringify(packageJson, null, 2) }
  ]
}

function sqlFromSchema(schema: any, product: any) {
  const tables = Array.isArray(schema && schema.tables) ? schema.tables : []
  const statements = tables.map(function (table: any) {
    const name = String(table.name || 'app_table').replace(/[^a-zA-Z0-9_]/g, '_')
    return 'create table if not exists ' + name + ' (\n  id uuid primary key default gen_random_uuid()\n);'
  })
  return '-- Generated for ' + product.name + '\n-- Review before applying.\n\n' + statements.join('\n\n') + '\n'
}

async function overview(productId: number) {
  const p = await product(productId)
  if (!p) throw new Error('Product not found')
  const run = await latestRun(productId)
  return {
    product: p,
    run: run || null,
    steps: run ? await steps(run.run_key) : [],
    artifacts: run ? await artifacts(run.run_key) : [],
    providers: providerHealth(),
    runs: await runs(productId)
  }
}

export async function executionOverview(productId: number) {
  if (!configured()) return { configured: false, product: null, run: null, steps: [], artifacts: [], providers: providerHealth(), runs: [] }
  return overview(productId)
}

export async function prepareExecution(productId: number, mode: 'dry_run' | 'live' = 'dry_run', requestedBy = 'founder') {
  if (!configured()) throw new Error('Supabase server credentials are not configured')
  const p = await product(productId)
  if (!p) throw new Error('Product not found')
  if (mode === 'live') {
    const health = providerHealth()
    const missing = ['github', 'vercel'].filter(function (key: string) {
      return !health[key as keyof typeof health].configured
    })
    if (missing.length) throw new Error('Live execution is blocked until required providers are configured: ' + missing.join(', '))
  }
  const current = await latestRun(productId)
  if (current && (current.status === 'queued' || current.status === 'running')) return overview(productId)

  const runKey = 'exec_' + Date.now().toString(36) + '_' + hash(String(productId) + ':' + Date.now())
  await createRun({
    run_key: runKey,
    product_id: productId,
    mode: mode,
    status: 'queued',
    requested_by: requestedBy,
    metadata: { engine: 'execution_layer_v1' }
  })

  await createSteps(STEP_DEFS.map(function (stepDef: any, index: number) {
    return {
      run_key: runKey,
      step_key: stepDef.key,
      provider: stepDef.provider,
      order_index: index,
      status: 'pending',
      idempotency_key: runKey + '|' + stepDef.key,
      input: {},
      output: {}
    }
  }))

  await patchProduct(productId, { execution_status: 'queued', execution_last_run: runKey })
  return overview(productId)
}

async function executeStep(run: any, current: any) {
  const p = await product(Number(run.product_id))
  if (!p) throw new Error('Product not found')

  await updateStep(run.run_key, current.step_key, { status: 'running', started_at: new Date().toISOString(), error: null })

  try {
    let output: any = {}

    if (current.step_key === 'spec_validation') {
      if (!p.thesis || !p.target_customer || !p.business_model) throw new Error('Product specification is incomplete')
      output = { valid: true, product_id: p.id }
    }

    if (current.step_key === 'build_agent_scaffold') {
      const factoryArtifacts = await productArtifacts(p.id)
      const features = await productFeatures(p.id)
      const files = buildFiles(p, factoryArtifacts, features)
      const existing = await artifacts(run.run_key)
      const existingPaths = new Set(existing.filter(function (item: any) {
        return item.artifact_type === 'execution_file' && item.path
      }).map(function (item: any) { return item.path }))
      const pendingFiles = files.filter(function (file: any) { return !existingPaths.has(file.path) })
      if (pendingFiles.length) await createArtifacts(pendingFiles.map(function (file: any) {
        return {
          run_key: run.run_key,
          artifact_type: 'execution_file',
          title: file.path,
          path: file.path,
          content: file.content,
          content_hash: hash(file.content),
          status: 'generated',
          metadata: { source: 'product_factory' }
        }
      }))
      output = { generated: true, file_count: files.length, created_file_count: pendingFiles.length, idempotent: pendingFiles.length === 0 }
    }

    if (current.step_key === 'github_provision') {
      if (!providerHealth().github.configured) {
        await updateStep(run.run_key, current.step_key, {
          status: 'blocked',
          completed_at: new Date().toISOString(),
          error: 'GITHUB_TOKEN is not configured'
        })
        return { blocked: true, message: 'GITHUB_TOKEN is not configured' }
      }
      const runArtifacts = await artifacts(run.run_key)
      const files = runArtifacts.filter(function (item: any) {
        return item.artifact_type === 'execution_file' && item.content
      }).map(function (item: any) {
        return { path: item.path, content: item.content }
      })
      const result = await githubProvision(p, files)
      output = result
      await patchProduct(p.id, {
        repository_name: result.repo,
        repository_owner: result.owner,
        repository_url: result.url,
        execution_status: 'repository_ready'
      })
      await updateRun(run.run_key, { repository_url: result.url })
    }

    if (current.step_key === 'figma_handoff') {
      const result = await figmaValidate()
      const manifest = {
        product_id: p.id,
        product_name: p.name,
        figma: result,
        generated_at: new Date().toISOString(),
        source: 'VentureOS'
      }
      await createArtifacts([{
        run_key: run.run_key,
        artifact_type: 'figma_handoff',
        title: 'Figma Handoff Manifest',
        path: 'design/figma-handoff.json',
        content: JSON.stringify(manifest, null, 2),
        content_hash: hash(JSON.stringify(manifest)),
        external_url: result.url || null,
        status: result.linked ? 'verified' : 'ready',
        metadata: {}
      }])
      output = result
      if (result.url) await patchProduct(p.id, { figma_file_url: result.url })
    }

    if (current.step_key === 'supabase_schema') {
      const factoryArtifacts = await productArtifacts(p.id)
      let schema: any = {}
      for (const row of factoryArtifacts) {
        if (row.artifact_type === 'schema') {
          schema = row.content || {}
          break
        }
      }
      const sql = sqlFromSchema(schema, p)
      await createArtifacts([{
        run_key: run.run_key,
        artifact_type: 'supabase_migration',
        title: 'Generated Supabase Migration',
        path: 'supabase/migrations/001_initial.sql',
        content: sql,
        content_hash: hash(sql),
        status: 'generated',
        metadata: { target: process.env.EXECUTION_SUPABASE_PROJECT_REF || null }
      }])
      output = {
        generated: true,
        project_ref: process.env.EXECUTION_SUPABASE_PROJECT_REF || null,
        applied: false,
        message: 'Migration generated; target application remains explicitly gated.'
      }
    }

    if (current.step_key === 'vercel_deploy') {
      if (!providerHealth().vercel.configured) throw new Error('VERCEL_TOKEN is not configured')
      if (!p.repository_owner || !p.repository_name) throw new Error('GitHub repository is required before Vercel deployment')
      const result = await vercelDeploy(p, p.repository_owner, p.repository_name)
      output = result
      await patchProduct(p.id, {
        vercel_project_id: result.projectName,
        execution_status: 'deployment_queued',
        deployment_url: result.url || null
      })
      await updateRun(run.run_key, {
        vercel_project_id: result.projectName,
        deployment_url: result.url || null
      })
    }

    if (current.step_key === 'build_verification') {
      const deployStep = await step(run.run_key, 'vercel_deploy')
      const deploymentId = deployStep && deployStep.output ? deployStep.output.deploymentId : null
      if (!deploymentId) throw new Error('No Vercel deployment id found')
      const result = await vercelStatus(String(deploymentId))
      if (result.state === 'READY' || result.state === 'ready') {
        output = { verified: true, ...result }
        await patchProduct(p.id, { execution_status: 'live', deployment_url: result.url || null })
      } else if (result.state === 'ERROR' || result.state === 'error' || result.state === 'CANCELED' || result.state === 'canceled') {
        await patchProduct(p.id, { execution_status: 'failed' })
        throw new Error('Vercel deployment verification failed with state ' + result.state)
      } else {
        output = { pending: true, verified: false, ...result }
      }
    }

    const stepStatus = output && output.blocked ? 'blocked' : output && output.pending ? 'pending' : 'completed'
    await updateStep(run.run_key, current.step_key, {
      status: stepStatus,
      output: output,
      completed_at: stepStatus === 'completed' || stepStatus === 'blocked' ? new Date().toISOString() : null
    })
    return output
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    await updateStep(run.run_key, current.step_key, {
      status: 'failed',
      error: message,
      completed_at: new Date().toISOString()
    })
    throw error
  }
}

export async function runNextStep(runKey: string, requestedStep?: string) {
  if (!configured()) throw new Error('Supabase server credentials are not configured')
  const run = await runByKey(runKey)
  if (!run) throw new Error('Execution run not found')

  const allSteps = await steps(runKey)
  if (run.status === 'running') return overview(Number(run.product_id))
  let current: any = null
  if (requestedStep) {
    for (const item of allSteps) {
      if (item.step_key === requestedStep) {
        current = item
        break
      }
    }
    if (!current) throw new Error('Execution step not found: ' + requestedStep)
    if (current.status === 'completed') return overview(Number(run.product_id))
  } else {
    for (const item of allSteps) {
      if (item.status !== 'completed') {
        current = item
        break
      }
    }
  }

  if (!current) return overview(Number(run.product_id))

  for (const previous of allSteps) {
    if (previous.order_index < current.order_index && previous.status !== 'completed') {
      throw new Error('Step ' + current.step_key + ' is blocked until ' + previous.step_key + ' is completed')
    }
  }

  await updateRun(runKey, {
    status: 'running',
    started_at: run.started_at || new Date().toISOString(),
    error: null
  })

  try {
    await executeStep(run, current)
  } catch (error) {
    const failedStep = await step(runKey, current.step_key)
    await updateRun(runKey, {
      status: 'partial',
      error: failedStep && failedStep.error ? failedStep.error : String(error)
    })
    return overview(Number(run.product_id))
  }

  const after = await steps(runKey)
  let completed = 0
  let failed = false
  for (const item of after) {
    if (item.status === 'completed') completed++
    if (item.status === 'failed' || item.status === 'blocked') failed = true
  }

  const nextStatus = failed ? 'partial' : completed === after.length ? 'completed' : 'queued'
  await updateRun(runKey, {
    status: nextStatus,
    completed_at: nextStatus === 'completed' ? new Date().toISOString() : null
  })

  if (nextStatus === 'completed') {
    await patchProduct(Number(run.product_id), { execution_status: run.mode === 'live' ? 'live' : 'completed' })
  }

  return overview(Number(run.product_id))
}