function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env['SUPA'+'BASE_SERVICE_ROLE_KEY']||process.env['SUPA'+'BASE_SECRET_KEY'];if(!url||!key)return null;return{url:url.replace(/\/$/,''),key}}
async function request(path:string,init:RequestInit={}){const d=db();if(!d)throw new Error('Supabase server credentials are not configured');const r=await fetch(d.url+'/rest/v1/'+path,{...init,headers:{apikey:d.key,Authorization:'Bearer '+d.key,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'});if(!r.ok)throw new Error('Supabase '+r.status+': '+await r.text());return r.status===204?null:r.json()}
export const configured=()=>!!db()
export async function product(productId:number){const rows=await request('ventureos_products?select=*&id=eq.'+productId+'&limit=1');return rows?.[0]??null}
export async function latestRun(productId:number){const rows=await request('ventureos_execution_runs?select=*&product_id=eq.'+productId+'&order=created_at.desc&limit=1');return rows?.[0]??null}
export async function runByKey(runKey:string){const rows=await request('ventureos_execution_runs?select=*&run_key=eq.'+encodeURIComponent(runKey)+'&limit=1');return rows?.[0]??null}
export async function runs(productId:number,limit=20){return request('ventureos_execution_runs?select=*&product_id=eq.'+productId+'&order=created_at.desc&limit='+Math.min(limit,100))}
export async function steps(runKey:string){return request('ventureos_execution_steps?select=*&run_key=eq.'+encodeURIComponent(runKey)+'&order=order_index.asc')}
export async function artifacts(runKey:string){return request('ventureos_execution_artifacts?select=*&run_key=eq.'+encodeURIComponent(runKey)+'&order=created_at.asc')}
export async function createRun(row:Record<string,unknown>){return(await request('ventureos_execution_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function updateRun(runKey:string,row:Record<string,unknown>){const rows=await request('ventureos_execution_runs?run_key=eq.'+encodeURIComponent(runKey),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return rows?.[0]??null}
export async function createSteps(rows:Record<string,unknown>[]){if(!rows.length)return;await request('ventureos_execution_steps?on_conflict=run_key,step_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}
export async function step(runKey:string,stepKey:string){const rows=await request('ventureos_execution_steps?run_key=eq.'+encodeURIComponent(runKey)+'&step_key=eq.'+encodeURIComponent(stepKey)+'&limit=1');return rows?.[0]??null}
export async function updateStep(runKey:string,stepKey:string,row:Record<string,unknown>){const rows=await request('ventureos_execution_steps?run_key=eq.'+encodeURIComponent(runKey)+'&step_key=eq.'+encodeURIComponent(stepKey),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return rows?.[0]??null}
export async function createArtifacts(rows:Record<string,unknown>[]){if(rows.length)await request('ventureos_execution_artifacts?on_conflict=run_key,artifact_type,path,content_hash',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)})}
export async function patchProduct(productId:number,row:Record<string,unknown>){const rows=await request('ventureos_products?id=eq.'+productId,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return rows?.[0]??null}