'use client'
import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,Box,BrainCircuit,CheckCircle2,ChevronRight,Clock3,Factory,Layers3,Loader2,Plus,RefreshCw,Sparkles,Target,Workflow} from 'lucide-react'

function Score({value}:{value:any}){return <span className="p7-score">{Math.round(Number(value||0))}</span>}
function Status({value}:{value:string}){return <span className={'p7-status '+(value||'draft')}>{String(value||'draft').replace('_',' ')}</span>}

export default function ProductFactory(){
 const [opps,setOpps]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[loading,setLoading]=useState(true),[configured,setConfigured]=useState(true),[busy,setBusy]=useState<number|null>(null),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);try{const [o,p]=await Promise.all([fetch('/api/opportunities',{cache:'no-store'}).then(r=>r.json()),fetch('/api/products',{cache:'no-store'}).then(r=>r.json())]);setConfigured(Boolean(o.configured&&p.configured));setOpps(o.opportunities||[]);setProducts(p.products||[]);if(!o.configured||!p.configured)setMessage(o.message||p.message||'Server data connection is not configured.')}catch(e){setMessage(String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const build=async(id:number)=>{setBusy(id);setMessage('');try{const r=await fetch('/api/products/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({opportunity_id:id})});const j=await r.json();if(!j.ok)throw new Error(j.error||j.message||'Product generation failed');window.location.href='/factory/'+j.product.id}catch(e){setMessage(e instanceof Error?e.message:String(e));setBusy(null)}}
 const sorted=useMemo(()=>[...opps].sort((a,b)=>Number(b.overall_score||0)-Number(a.overall_score||0)),[opps])
 return <div className="phase7-shell">
  <div className="phase7-top"><div><div className="eyebrow">VENTUREOS / PHASE 7</div><h1>Product Factory</h1><p>Turn a validated opportunity into a build-ready product specification without losing the evidence, economics or constraints that created the opportunity.</p></div><div className="phase7-actions"><button className="p7-btn" onClick={load}><RefreshCw size={14}/> Refresh</button></div></div>
  <div className="p7-pipeline"><div className="p7-pipeline-node active"><span>01</span><b>Opportunity</b><small>Validated thesis</small></div><ArrowRight size={14}/><div className="p7-pipeline-node active"><span>02</span><b>Build this</b><small>Factory handoff</small></div><ArrowRight size={14}/><div className="p7-pipeline-node"><span>03</span><b>Product spec</b><small>PRD · UX · API · Schema</small></div><ArrowRight size={14}/><div className="p7-pipeline-node"><span>04</span><b>MVP plan</b><small>Milestones · analytics</small></div></div>
  {!configured&&<div className="p7-alert"><BrainCircuit size={16}/><div><b>Product Factory is in configuration mode.</b><span>{message||'Connect the server-side data layer to generate and persist product specs.'}</span></div></div>}
  {message&&configured&&<div className="p7-alert subtle"><Clock3 size={15}/><div><b>{message}</b></div></div>}
  <section className="p7-stats"><div><span>OPPORTUNITIES READY</span><b>{sorted.length}</b><small>Validated inputs available to Factory</small></div><div><span>PRODUCTS GENERATED</span><b>{products.length}</b><small>Persistent Factory outputs</small></div><div><span>ARTIFACTS / PRODUCT</span><b>11</b><small>PRD → pricing hypothesis</small></div><div><span>ARCHITECTURE MODE</span><b>Evidence-first</b><small>Structured, auditable outputs</small></div></section>
  <section className="p7-grid">
   <div className="p7-panel"><div className="p7-head"><div><b>Opportunity queue</b><span>Select a validated opportunity and build the first product specification.</span></div><Target size={15}/></div>
    <div className="p7-opportunity-list">{loading?<div className="p7-empty"><Loader2 className="spin" size={20}/><b>Loading opportunity intelligence…</b></div>:!sorted.length?<div className="p7-empty"><Factory size={24}/><b>No opportunities available</b><span>Run the Phase 2–5 intelligence pipeline first. Product Factory will never invent an opportunity as an input.</span></div>:sorted.map((o:any)=><article className="p7-opportunity" key={o.id}><div className="p7-opp-rank"><span>OPP</span><b>{String(o.id).padStart(3,'0')}</b></div><div className="p7-opp-main"><div className="p7-opp-title"><b>{o.title}</b><Status value={o.status}/></div><p>{o.summary}</p><div className="p7-opp-meta"><span>{o.industry||'General'}</span><span>{o.target_audience||'Audience pending'}</span><span>{o.evidence_count||0} evidence</span><span>{o.source_count||0} sources</span></div><div className="p7-score-row"><span>Demand <Score value={o.demand_score}/></span><span>WTP <Score value={o.monetization_score}/></span><span>Evidence <Score value={o.evidence_quality_score}/></span></div></div><div className="p7-opp-action"><b>{Math.round(o.overall_score||0)}</b><button className="p7-primary" onClick={()=>build(Number(o.id))} disabled={busy===Number(o.id)||!configured}>{busy===Number(o.id)?<><Loader2 size={13} className="spin"/> Building</>:<><Sparkles size={13}/> Build this</>}</button><a href={'/opportunities/'+o.id}>View thesis <ChevronRight size={11}/></a></div></article>)}</div>
   </div>
   <aside className="p7-side"><div className="p7-panel"><div className="p7-head"><div><b>Factory output</b><span>Generated products stay linked to their originating opportunity.</span></div><Box size={15}/></div><div className="p7-product-list">{products.length?products.map((p:any)=><a key={p.id} href={'/factory/'+p.id} className="p7-product"><div className="p7-product-icon"><Workflow size={15}/></div><div><b>{p.name}</b><span>{p.business_model||'Business model pending'}</span><small>Created {new Date(p.created_at).toLocaleDateString()}</small></div><Status value={p.status}/></a>):<div className="p7-empty small"><Layers3 size={18}/><b>No products generated yet</b><span>Choose an opportunity and click Build this.</span></div>}</div></div>
   <div className="p7-panel"><div className="p7-head"><div><b>Factory contract</b><span>What the Architect produces every time</span></div></div><div className="p7-contract">{['PRD','Schema','API specification','Feature backlog','UX map','MVP milestones','Analytics plan','Economics','Pricing hypothesis','Validation plan','Architecture'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><CheckCircle2 size={12}/></div>)}</div></div></aside>
  </section>
 </div>
}
