export type EvidenceRow={id:number;signal_id:number|null;source_url:string;source_domain:string;source_type:string;claim_text:string;snippet:string|null;stance:string;evidence_status:string;source_confidence:number;evidence_score:number;published_at:string|null;entity_name:string|null;entity_domain:string|null;metadata:Record<string,unknown>}
export type TrendRow={id:number;trend_key:string;label:string;period_start:string;period_end:string;signal_count:number;unique_sources:number;momentum_score:number;confidence:number;industries:string[];audiences:string[];description:string|null}
export type MarketEvent={id:number;event_key:string;title:string;event_type:string;detected_at:string;impact_score:number;momentum_score:number;source_count:number;signal_count:number;confidence:number;description:string;industries:string[];audiences:string[];status:string}
export type CompetitorSnapshot={id:number;entity_domain:string;entity_name:string;snapshot_at:string;source_count:number;signal_count:number;change_score:number;confidence:number;pricing_signals:string[];product_signals:string[];latest_titles:string[];status:string}

const polarityUp=['increase','increased','rising','rise','growth','grew','higher','up','surge','launch','launched','funding','hired','hiring','expansion']
const polarityDown=['decrease','decreased','falling','fall','decline','declined','lower','down','shutdown','shut down','layoff','laid off','cut']
function polarity(text:string){const t=text.toLowerCase();const up=polarityUp.filter(x=>t.includes(x)).length,down=polarityDown.filter(x=>t.includes(x)).length;return up===down?'neutral':up>down?'positive':'negative'}
function domain(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return 'unknown'}}
export function sourceType(url:string,title:string){const d=domain(url);const t=(url+' '+title).toLowerCase();if(/\.gov$|\.gov\.|\.edu$|docs\.|developer\.|status\./.test(d))return 'official';if(/reuters|bloomberg|techcrunch|forbes|wsj|ft\.com|nytimes|theverge|wired/.test(d))return 'news';if(/reddit|quora|stackexchange|g2\.com|trustpilot/.test(d))return 'user_signal';if(/pricing|plans|customers|product|features|docs/.test(t))return 'competitor';return 'web'}
export function sourceConfidence(url:string,title:string,provider:string){const type=sourceType(url,title),base=type==='official'?0.94:type==='news'?0.84:type==='competitor'?0.82:type==='user_signal'?0.67:0.58;const providerAdj=provider==='tavily'?0.03:provider==='exa'?0.04:provider==='firecrawl'?0.02:0;return Math.min(0.99,base+providerAdj)}
export function evidenceScore(confidence:number,corroboration:number,recency:number,stance:string){const stanceAdj=stance==='supports'?1:stance==='contradicts'?0.78:0.88;return Math.round(Math.max(0,Math.min(100,confidence*45+corroboration*30+recency*25))*stanceAdj)}
export function signalStance(text:string){const p=polarity(text);return p==='neutral'?'neutral':'supports'}
export function contradictionPair(a:string,b:string){const pa=polarity(a),pb=polarity(b);return pa!=='neutral'&&pb!=='neutral'&&pa!==pb}
export function momentum(current:number,previous:number){if(previous===0)return current>0?100:0;return Math.max(-100,Math.min(100,Math.round(((current-previous)/previous)*100)))}
export function eventType(text:string){const t=text.toLowerCase();if(/acquisition|acquired|merger/.test(t))return 'M&A';if(/funding|raised|series [a-z]/.test(t))return 'Funding';if(/pricing|price increase|price cut/.test(t))return 'Pricing';if(/launch|released|release|rollout/.test(t))return 'Product launch';if(/shutdown|shut down|closed/.test(t))return 'Shutdown';if(/hiring|recruit|layoff/.test(t))return 'Workforce';if(/regulation|policy|compliance/.test(t))return 'Regulatory';return 'Market change'}
export function trendDescription(label:string,count:number,m:number){return label+' trend has '+count+' normalized signals in the current window with '+(m>=0?'+':'')+m+'% momentum versus the previous window.'}
export function competitorSignals(titles:string[]){const pricing=titles.filter(t=>/pricing|price|plan|cost/i.test(t)).slice(0,8),product=titles.filter(t=>/product|feature|launch|release|platform/i.test(t)).slice(0,8);return {pricing,product}}