import crypto from 'node:crypto'
import {evidenceScore,eventType,signalStance,sourceConfidence,sourceType,trendDescription,competitorSignals,momentum,contradictionPair} from './engine'
import {createMarketRun,finishMarketRun,evidenceFingerprint,insertCompetitor,insertEvidence as saveEvidence,signals,upsertEvent,upsertTrend} from './storage'
function uniq(v:any[]){return [...new Set(v.filter(Boolean))]}
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex')}
function domain(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return 'unknown'}}
function ageScore(iso:string|null){if(!iso)return .55;const age=(Date.now()-new Date(iso).getTime())/86400000;if(age<=1)return 1;if(age<=3)return .92;if(age<=7)return .82;if(age<=14)return .7;return .55}
function polarity(text:string){const t=text.toLowerCase();const up=['increase','increased','rising','rise','growth','grew','higher','up','surge','launch','launched','funding','hired','hiring','expansion'].filter(x=>t.includes(x)).length;const down=['decrease','decreased','falling','fall','decline','declined','lower','down','shutdown','shut down','layoff','laid off','cut'].filter(x=>t.includes(x)).length;return up===down?'neutral':up>down?'positive':'negative'}
export async function processMarketIntelligence(limit=1000){
 const runId='market_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);await createMarketRun(runId)
 let evidenceCreated=0,trendsUpdated=0,eventsUpdated=0,competitorsUpdated=0
 let rows:any[]=[]
 try{
  rows=await signals(limit) as any[]
  const now=Date.now(),week=7*86400000,twoWeeks=14*86400000
  const polar=rows.map(r=>({r,p:polarity((r.title||'')+' '+(r.normalized_text||''))}));
  for(const {r,p} of polar){
   const url=r.source_url||r.canonical_url, d=domain(url), type=sourceType(url,r.title||''), conf=sourceConfidence(url,r.title||'',String(r.metadata?.provider||'')), corroboration=Math.min(1,Number(r.occurrence_count||1)/4), recency=ageScore(r.last_seen_at), contradiction=polar.some(x=>x.r.id!==r.id&&x.r.industry===r.industry&&x.r.signal_type===r.signal_type&&contradictionPair((r.title||'')+' '+(r.normalized_text||''),(x.r.title||'')+' '+(x.r.normalized_text||''))), stance=contradiction?'contradicts':signalStance((r.title||'')+' '+(r.normalized_text||'')), status=contradiction?'contradictory':conf>=.72?'observed':'unverified', fp=hash(String(r.id)+'|'+url+'|'+(r.title||''));
   if(!await evidenceFingerprint(fp)){await saveEvidence({signal_id:r.id,source_run_id:r.source_run_id,source_url:url,source_domain:d,source_type:type,claim_text:r.title||'Observed market signal',snippet:(r.normalized_text||'').slice(0,1400),stance,evidence_status:status,source_confidence:conf,evidence_score:evidenceScore(conf,corroboration,recency,stance),published_at:r.metadata?.publishedAt||null,entity_name:r.entity_name||d,entity_domain:r.entity_domain||d,fingerprint:fp,metadata:{provider:r.metadata?.provider||null,contradiction_detected:contradiction,polarity:p}});evidenceCreated++}
  }
  const groups=new Map<string,any[]>();
  for(const r of rows){const key=(r.industry||'General')+'|'+(r.signal_type||'unknown');if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(r)}
  for(const [key,members] of groups){
   const current=members.filter(r=>now-new Date(r.last_seen_at).getTime()<=week),previous=members.filter(r=>{const a=now-new Date(r.last_seen_at).getTime();return a>week&&a<=twoWeeks}),trend=Math.round((current.reduce((a,r)=>a+Number(r.classification_confidence||0),0)/(current.length||1))),mk=momentum(current.length,previous.length),sources=uniq(current.map(r=>r.source_url)).length,industries=uniq(current.map(r=>r.industry)),audiences=uniq(current.map(r=>r.audience)),label=key.split('|').join(' · ');
   await upsertTrend({trend_key:key,label,period_start:new Date(now-week).toISOString(),period_end:new Date(now).toISOString(),signal_count:current.length,unique_sources:sources,momentum_score:mk,confidence:trend,industries,audiences,description:trendDescription(label,current.length,mk),updated_at:new Date().toISOString()});trendsUpdated++
  }
  const eventGroups=new Map<string,any[]>();for(const r of rows.filter(x=>x.signal_type==='market_change')){if(now-new Date(r.last_seen_at).getTime()>twoWeeks)continue;const k=eventType((r.title||'')+' '+(r.normalized_text||''))+'|'+(r.industry||'General');if(!eventGroups.has(k))eventGroups.set(k,[]);eventGroups.get(k)!.push(r)}
  for(const [key,members] of eventGroups){const et=key.split('|')[0],industry=key.split('|')[1],sources=uniq(members.map(r=>r.source_url)),impact=Math.min(99,Math.round(members.reduce((a,r)=>a+Number(r.urgency_score||0),0)/(members.length||1))),conf=Math.round(members.reduce((a,r)=>a+Number(r.classification_confidence||0),0)/(members.length||1)),current=members.filter(r=>now-new Date(r.last_seen_at).getTime()<=week).length,previous=members.filter(r=>{const a=now-new Date(r.last_seen_at).getTime();return a>week&&a<=twoWeeks}).length,mk=momentum(current,previous),title=et+' in '+industry;
   await upsertEvent({event_key:key,title,event_type:et,detected_at:new Date().toISOString(),impact_score:impact,momentum_score:mk,source_count:sources.length,signal_count:members.length,confidence:conf,description:members[0]?.normalized_text?.slice(0,420)||'Detected market movement backed by normalized signals.',industries:industry==='General'?[]:[industry],audiences:uniq(members.map(r=>r.audience)),status:'active',metadata:{source_urls:sources.slice(0,20)}});eventsUpdated++
  }
  const comps=new Map<string,any[]>();for(const r of rows.filter(x=>x.entity_domain)){const k=String(r.entity_domain);if(!comps.has(k))comps.set(k,[]);comps.get(k)!.push(r)}
  for(const [dom,members] of comps){const current=members.filter(r=>now-new Date(r.last_seen_at).getTime()<=week),previous=members.filter(r=>{const a=now-new Date(r.last_seen_at).getTime();return a>week&&a<=twoWeeks}),titles=uniq(members.map(r=>r.title)),change=momentum(current.length,previous.length),avg=Math.round(members.reduce((a,r)=>a+Number(r.classification_confidence||0),0)/(members.length||1)),cs=competitorSignals(titles);await insertCompetitor({entity_domain:dom,entity_name:members[0].entity_name||dom,snapshot_at:new Date().toISOString(),source_count:uniq(members.map(r=>r.source_url)).length,signal_count:members.length,change_score:change,confidence:avg,pricing_signals:cs.pricing,product_signals:cs.product,latest_titles:titles.slice(0,12),status:'observed',metadata:{current_7d:current.length,previous_7d:previous.length}});competitorsUpdated++}
  await finishMarketRun(runId,{processed_signals:rows.length,evidence_created:evidenceCreated,trends_updated:trendsUpdated,events_updated:eventsUpdated,competitors_updated:competitorsUpdated});return {runId,processedSignals:rows.length,evidenceCreated,trendsUpdated,eventsUpdated,competitorsUpdated}
 }catch(e){await finishMarketRun(runId,{processed_signals:rows.length,evidence_created:evidenceCreated,trends_updated:trendsUpdated,events_updated:eventsUpdated,competitors_updated:competitorsUpdated,error:e instanceof Error?e.message:'Market intelligence processing failed'});throw e}
}