function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY);if(!url||!key)return null;return{url:url.replace(/\/$/,''),key}}
async function request(path:string,init:RequestInit={}){const d=db();if(!d)throw new Error('Supabase server credentials are not configured');const r=await fetch(d.url+'/rest/v1/'+path,{...init,headers:{apikey:d.key,Authorization:'Bearer '+d.key,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'});if(!r.ok)throw new Error('Supabase '+r.status+': '+await r.text());return r.status===204?null:r.json()}
export async function signals(limit=1000){return request('ventureos_signals?select=*&order=last_seen_at.desc&limit='+Math.min(limit,1500))}
export async function evidence(limit=300){return request('ventureos_evidence?select=*&order=evidence_score.desc&limit='+Math.min(limit,500))}
export async function evidenceBySignal(signalId:number){return request('ventureos_evidence?select=*&signal_id=eq.'+signalId+'&order=evidence_score.desc&limit=100')}
export async function evidenceFingerprint(fp:string){const rows=await request('ventureos_evidence?select=*&fingerprint=eq.'+encodeURIComponent(fp)+'&limit=1');return rows?.[0]??null}
export async function insertEvidence(row:Record<string,unknown>){const [r]=await request('ventureos_evidence',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return r}
export async function updateEvidence(id:number,patch:Record<string,unknown>){const [r]=await request('ventureos_evidence?id=eq.'+id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});return r}
export async function upsertTrend(row:Record<string,unknown>){const q=await request('ventureos_trends?select=*&trend_key=eq.'+encodeURIComponent(String(row.trend_key))+'&limit=1');if(q?.[0]){const [r]=await request('ventureos_trends?id=eq.'+q[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return r}return (await request('ventureos_trends',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function upsertEvent(row:Record<string,unknown>){const q=await request('ventureos_market_events?select=*&event_key=eq.'+encodeURIComponent(String(row.event_key))+'&limit=1');if(q?.[0]){const [r]=await request('ventureos_market_events?id=eq.'+q[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return r}return (await request('ventureos_market_events',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function insertCompetitor(row:Record<string,unknown>){return (await request('ventureos_competitor_snapshots',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function createMarketRun(id:string){return (await request('ventureos_market_processing_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({run_id:id,status:'running'})}))[0]}
export async function finishMarketRun(id:string,patch:Record<string,unknown>){await request('ventureos_market_processing_runs?run_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...patch,status:patch.error?'partial':'completed',completed_at:new Date().toISOString()})})}
export async function trends(limit=50){return request('ventureos_trends?select=*&order=momentum_score.desc&limit='+Math.min(limit,100))}
export async function marketEvents(limit=50){return request('ventureos_market_events?select=*&order=detected_at.desc&limit='+Math.min(limit,100))}
export async function competitors(limit=50){return request('ventureos_competitor_snapshots?select=*&order=change_score.desc,snapshot_at.desc&limit='+Math.min(limit,100))}
export async function marketRunStats(){return request('ventureos_market_processing_runs?select=*&order=started_at.desc&limit=20')}