
'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,BrainCircuit,Check,Compass,History,Lightbulb,Plus,RefreshCw,Save,Search,Target,UserRound,X} from 'lucide-react'
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean)
export default function Memory(){const [data,setData]=useState<any>({}),[tab,setTab]=useState<'profile'|'decisions'|'lessons'|'context'>('profile'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[ctx,setCtx]=useState<any>(null),[query,setQuery]=useState(''),[profile,setProfile]=useState<any>({display_name:'',role:'',bio:'',capabilities:[],markets:[],preferred_business_models:[],distribution_strengths:[],technical_capabilities:[]}),[decision,setDecision]=useState<any>({decision_type:'rejected',title:'',rationale:'',tags:''}),[lesson,setLesson]=useState<any>({title:'',lesson:'',category:'',confidence:70})
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/memory',{cache:'no-store'}),j=await r.json();setData(j);if(j.profile)setProfile(j.profile)}finally{setLoading(false)}};useEffect(()=>{load()},[])
 const saveProfile=async()=>{setSaving(true);try{await fetch('/api/memory/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});await load()}finally{setSaving(false)}}
 const saveDecision=async()=>{setSaving(true);try{await fetch('/api/memory/decisions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...decision,tags:split(decision.tags)})});setDecision({decision_type:'rejected',title:'',rationale:'',tags:''});await load()}finally{setSaving(false)}}
 const saveLesson=async()=>{setSaving(true);try{await fetch('/api/memory/lessons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lesson)});setLesson({title:'',lesson:'',category:'',confidence:70});await load()}finally{setSaving(false)}}
 const searchContext=async()=>{const r=await fetch('/api/memory/context?q='+encodeURIComponent(query),{cache:'no-store'});setCtx(await r.json())}
 const decisions=data.decisions||[],rejected=decisions.filter((x:any)=>['rejected','killed'].includes(x.decision_type)),vector=useMemo(()=>Object.entries(data.preferenceVector||{}).slice(0,16),[data.preferenceVector])
 return <div className="phase6-shell"><div className="phase6-top"><div><div className="eyebrow">VENTUREOS / FOUNDER MEMORY</div><h1>Remember how you build.</h1><p>Founder DNA, preferences, decisions, rejected ideas and lessons become reusable operating context.</p></div><button className="p2-btn" onClick={load}><RefreshCw size={14}/> Refresh</button></div>
 {!data.configured&&<div className="p6-alert"><AlertTriangle size={16}/><div><b>Founder Memory is in configuration mode.</b><span>{data.message||'Connect the server-side Supabase credentials to persist founder context.'}</span></div></div>}
 {data.configured&&<><div className="p6-memory-tabs">{[['profile',UserRound,'Founder DNA'],['decisions',History,'Decisions & rejected ideas'],['lessons',Lightbulb,'Lessons'],['context',Compass,'Context retrieval']].map(([id,I,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={14}/>{label}</button>)}</div>
 {tab==='profile'&&<section className="p6-memory-grid"><div className="p6-panel"><div className="p6-head"><div><b>Founder DNA</b><span>Editable long-term profile</span></div><BrainCircuit size={16}/></div><div className="p6-form"><label>Display name<input value={profile.display_name||''} onChange={(e:any)=>setProfile({...profile,display_name:e.target.value})}/></label><label>Role<input value={profile.role||''} onChange={(e:any)=>setProfile({...profile,role:e.target.value})}/></label><label>Bio<textarea value={profile.bio||''} onChange={(e:any)=>setProfile({...profile,bio:e.target.value})}/></label>{[['capabilities','Capabilities'],['markets','Markets'],['preferred_business_models','Preferred business models'],['distribution_strengths','Distribution strengths'],['technical_capabilities','Technical capabilities']].map(([k,l])=><label key={k}>{l}<input value={(profile[k]||[]).join(', ')} onChange={(e:any)=>setProfile({...profile,[k]:split(e.target.value)})}/></label>)}<button className="p2-primary" disabled={saving} onClick={saveProfile}><Save size={14}/>{saving?'Saving…':'Save founder profile'}</button></div></div><aside><div className="p6-panel"><div className="p6-head"><div><b>Preference vector</b><span>Signals learned from explicit preferences + decisions</span></div></div><div className="p6-vector">{vector.map(([k,v]:any)=><div key={k}><span>{k}</span><b>{Number(v).toFixed(2)}</b><i><em style={{width:Math.min(100,Math.abs(Number(v))*35)+'%',marginLeft:Number(v)<0?'auto':0}}/></i></div>)}{!vector.length&&<div className="p6-empty small">No preference vector yet. Record decisions or add profile preferences.</div>}</div></div><div className="p6-panel"><div className="p6-head"><div><b>Memory inventory</b><span>Persistent founder context</span></div></div><div className="p6-inventory"><div><b>{(data.memory||[]).length}</b><span>memories</span></div><div><b>{decisions.length}</b><span>decisions</span></div><div><b>{(data.lessons||[]).length}</b><span>lessons</span></div><div><b>{(data.prefs||[]).length}</b><span>preferences</span></div></div></div></aside></section>}
 {tab==='decisions'&&<section className="p6-memory-grid"><div className="p6-panel"><div className="p6-head"><div><b>Record a founder decision</b><span>Accepted, rejected, deferred or killed ideas become reusable context.</span></div><Target size={16}/></div><div className="p6-form"><label>Decision type<select value={decision.decision_type} onChange={(e:any)=>setDecision({...decision,decision_type:e.target.value})}><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="deferred">Deferred</option><option value="killed">Killed</option></select></label><label>Idea / subject<input value={decision.title} onChange={(e:any)=>setDecision({...decision,title:e.target.value})}/></label><label>Why<textarea value={decision.rationale} onChange={(e:any)=>setDecision({...decision,rationale:e.target.value})}/></label><label>Tags<input value={decision.tags} onChange={(e:any)=>setDecision({...decision,tags:e.target.value})} placeholder="distribution, agency, b2b, hardware"/></label><button className="p2-primary" disabled={saving||!decision.title.trim()} onClick={saveDecision}><Plus size={14}/>{saving?'Saving…':'Record decision'}</button></div></div><div className="p6-panel"><div className="p6-head"><div><b>Rejected ideas & decisions</b><span>Failure memory is intentionally preserved.</span></div><X size={15}/></div><div className="p6-decision-list">{rejected.map((x:any)=><article key={x.id}><span className="p6-decision-type">{x.decision_type}</span><b>{x.title}</b><p>{x.rationale||'No rationale recorded.'}</p><small>{new Date(x.decided_at).toLocaleString()}</small></article>)}{!rejected.length&&<div className="p6-empty small">No rejected or killed ideas recorded yet.</div>}</div></div></section>}
 {tab==='lessons'&&<section className="p6-memory-grid"><div className="p6-panel"><div className="p6-head"><div><b>Capture a lesson</b><span>Turn experience into reusable operating memory.</span></div><Lightbulb size={16}/></div><div className="p6-form"><label>Lesson title<input value={lesson.title} onChange={(e:any)=>setLesson({...lesson,title:e.target.value})}/></label><label>Lesson<textarea value={lesson.lesson} onChange={(e:any)=>setLesson({...lesson,lesson:e.target.value})}/></label><label>Category<input value={lesson.category} onChange={(e:any)=>setLesson({...lesson,category:e.target.value})}/></label><label>Confidence<input type="number" min="0" max="100" value={lesson.confidence} onChange={(e:any)=>setLesson({...lesson,confidence:Number(e.target.value)})}/></label><button className="p2-primary" disabled={saving||!lesson.lesson.trim()} onClick={saveLesson}><Plus size={14}/>{saving?'Saving…':'Save lesson'}</button></div></div><div className="p6-panel"><div className="p6-head"><div><b>Founder lessons</b><span>High-importance learnings surfaced first.</span></div></div><div className="p6-decision-list">{(data.lessons||[]).map((x:any)=><article key={x.id}><span className="p6-decision-type">{x.category||'general'}</span><b>{x.title}</b><p>{x.lesson}</p><small>{Math.round(x.confidence)} confidence · {new Date(x.learned_at).toLocaleDateString()}</small></article>)}</div></div></section>}
 {tab==='context'&&<section className="p6-context"><div className="p6-panel"><div className="p6-head"><div><b>Founder Context Retrieval</b><span>Ask what the system should remember before making a decision.</span></div><Search size={16}/></div><div className="p6-context-form"><input value={query} onChange={(e:any)=>setQuery(e.target.value)} onKeyDown={(e:any)=>{if(e.key==='Enter')searchContext()}} placeholder="e.g. What kinds of B2B ideas have I rejected and why?"/><button className="p2-primary" onClick={searchContext}><Search size={14}/> Retrieve</button></div></div>{ctx?.configured&&<><div className="p6-panel"><div className="p6-head"><div><b>Preference vector</b><span>Context retrieved for this query</span></div></div><div className="p6-tags">{Object.entries(ctx.preferenceVector||{}).slice(0,20).map(([k,v]:any)=><span key={k}>{k}: {Number(v).toFixed(2)}</span>)}</div></div><div className="p6-panel"><div className="p6-head"><div><b>Relevant memory</b><span>{(ctx.results||[]).length} records matched</span></div></div><div className="p6-memory-results">{(ctx.results||[]).map((x:any,i:number)=><article key={i}><span>{x.memory_type||x.source_type||'memory'}</span><b>{x.title||x.preference_key}</b><p>{x.content||x.lesson||x.rationale||JSON.stringify(x.value||x.structured_value||{})}</p><small>score {Math.round(x._score||0)}</small></article>)}</div></div></>}</section>}
 </>}
 </div>}
