
'use client'
import {useEffect,useState} from 'react'
import {ArrowLeft,ArrowRight,BarChart3,CalendarClock,CheckCircle2,CircleDollarSign,ExternalLink,Factory,History,Link2,Loader2,PauseCircle,Rocket,Skull,Target,Users,Workflow} from 'lucide-react'

const STATES=[['ideas','Ideas'],['validation','Validation'],['mvp','MVP'],['building','Building'],['beta','Beta'],['live','Live'],['paused','Paused'],['archived','Archived'],['killed','Killed']] as const
function money(n:any){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}
function pretty(s:string){return s?s.charAt(0).toUpperCase()+s.slice(1):''}
export default function PortfolioDetail({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState('')
 const load=async()=>{if(!id)return;setLoading(true);try{const r=await fetch('/api/portfolio/'+id,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Portfolio detail failed');setData(j)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{params.then(x=>setId(x.id))},[params]);useEffect(()=>{load()},[id])
 const transition=async(to:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/portfolio/'+id+'/transition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to_status:to,reason})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Transition failed');setReason('');setData(j)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(loading)return <main className="p8-shell"><div className="p8-panel p8-empty"><Loader2 className="spin" size={22}/><strong>Loading product lifecycle…</strong></div></main>
 if(error||!data?.product)return <main className="p8-shell"><div className="p8-banner"><span>{error||'Product not found'}</span></div></main>
 const p=data.product,history=data.history||[],metrics=data.metrics||[],current=String(p.status||'ideas')
 const nextIndex=STATES.findIndex(s=>s[0]===current)
 const allowed=nextIndex>=0?STATES.map((s,i)=>({k:s[0],l:s[1],i})).filter(x=>iTransition(current,x.k)).filter(x=>x.k!==current):[]
 function iTransition(from:string,to:string){const map:any={ideas:['validation','killed','archived'],validation:['mvp','ideas','killed','archived'],mvp:['building','validation','killed','archived'],building:['beta','mvp','paused','killed'],beta:['live','building','paused','killed'],live:['paused','archived'],paused:['building','beta','live','archived','killed'],archived:['ideas'],killed:['ideas']};return (map[from]||[]).includes(to)}
 return <main className="p8-shell">
  <div className="p8-detail-nav"><button className="p8-btn" onClick={()=>window.location.href='/portfolio'}><ArrowLeft size={13}/> Portfolio</button><span>PRODUCT #{String(p.id).padStart(3,'0')}</span><span className={'p8-detail-status '+current}>{pretty(current)}</span></div>
  <section className="p8-hero"><div><div className="p8-eyebrow">PRODUCT LIFECYCLE / ORIGIN OPPORTUNITY</div><h1>{p.name}</h1><p>{p.thesis||p.problem_statement||'No thesis recorded.'}</p><div className="p8-tags"><span>{p.business_model||'Business model pending'}</span><span>{p.current_phase||pretty(current)}</span>{p.metadata?.opportunity_title&&<span>From {p.metadata.opportunity_title}</span>}</div></div><div className="p8-hero-progress"><small>LIFECYCLE PROGRESS</small><b>{Math.round(p.progress||0)}%</b><i><em style={{width:Math.min(100,Math.max(0,Number(p.progress||0)))+'%'}}/></i><span>{p.next_milestone||'No next milestone set'}</span></div></section>
  <section className="p8-stage-flow">{STATES.map(([key,label],i)=><div key={key} className={'p8-stage '+(key===current?'current':'')+(i<nextIndex?' passed':'')}><span>{String(i+1).padStart(2,'0')}</span><b>{label}</b>{i<STATES.length-1&&<ArrowRight size={11}/>}</div>)}</section>
  <section className="p8-detail-grid">
   <div className="p8-panel"><div className="p8-section-head"><div><b>Portfolio metrics</b><span>Current product economics and operating footprint.</span></div><BarChart3 size={15}/></div><div className="p8-detail-metrics"><div><Users size={13}/><span>Customers</span><b>{Number(p.customer_count||0)}</b></div><div><CircleDollarSign size={13}/><span>MRR</span><b>{money(p.mrr)}</b></div><div><BarChart3 size={13}/><span>API cost</span><b>{money(p.api_cost)}</b></div><div><CircleDollarSign size={13}/><span>Gross margin</span><b>{money(p.gross_margin)}</b></div></div>{metrics.length?<div className="p8-table">{metrics.slice(0,12).map((m:any)=><div key={m.id}><span>{m.metric_date}</span><b>{Number(m.customer_count||0)} customers</b><b>{money(m.mrr)} MRR</b><b>{money(m.api_cost)} cost</b><b>{money(m.gross_margin)} margin</b></div>)}</div>:<div className="p8-empty compact"><span>No historical metric snapshots recorded yet.</span></div>}</div>
   <aside className="p8-stack"><div className="p8-panel"><div className="p8-section-head"><div><b>Execution links</b><span>Repository and deployed product surface.</span></div><Link2 size={15}/></div><div className="p8-link-list">{p.repository_url?<a href={p.repository_url} target="_blank" rel="noreferrer"><Workflow size={14}/><div><b>Repository</b><small>{p.repository_url}</small></div><ExternalLink size={12}/></a>:<div className="p8-link-pending"><Workflow size={14}/><div><b>Repository</b><small>Not linked yet</small></div></div>}{p.deployment_url?<a href={p.deployment_url} target="_blank" rel="noreferrer"><Rocket size={14}/><div><b>Deployment</b><small>{p.deployment_url}</small></div><ExternalLink size={12}/></a>:<div className="p8-link-pending"><Rocket size={14}/><div><b>Deployment</b><small>Not linked yet</small></div></div>}</div></div>
   <div className="p8-panel"><div className="p8-section-head"><div><b>Move lifecycle</b><span>Validated state-machine transitions only.</span></div></div><textarea className="p8-reason" value={reason} onChange={(e:any)=>setReason(e.target.value)} placeholder="Optional transition reason…"/><div className="p8-transition-grid">{allowed.map(x=><button key={x.k} className="p8-transition" onClick={()=>transition(x.k)} disabled={busy}><span>{x.l}</span><ArrowRight size={11}/></button>)}{!allowed.length&&<div className="p8-muted">No valid transitions from {pretty(current)}.</div>}</div></div></aside>
  </section>
  <section className="p8-panel p8-history-panel"><div className="p8-section-head"><div><b>Lifecycle history</b><span>Immutable product state transitions with reasons and timestamps.</span></div><History size={15}/></div>{history.length?<div className="p8-history">{history.map((h:any)=><div key={h.id} className="p8-history-row"><div className="p8-history-dot"/><div><b>{pretty(h.to_status)}</b><span>{h.from_status?pretty(h.from_status)+' → ':''}{pretty(h.to_status)}</span><small>{h.reason||'No reason recorded'} · {new Date(h.created_at).toLocaleString()}</small></div></div>)}</div>:<div className="p8-empty compact"><History size={18}/><strong>No lifecycle history yet</strong><span>The first transition will create an auditable checkpoint.</span></div>}</section>
  <footer className="p8-footer"><span>VentureOS Phase 8 · Product lifecycle control plane</span><span>Origin: {p.metadata?.opportunity_title||'Opportunity record'}</span></footer>
 </main>
}
