'use client'
import {useState} from 'react'
import {AlertTriangle,ExternalLink,FlaskConical,RefreshCw,Search,Zap} from 'lucide-react'
export default function Research(){
 const [query,setQuery]=useState('What changed in AI, SaaS, automation and SMB software in the last 24 hours?'),[mode,setMode]=useState<'normal'|'deep'|'max'>('deep'),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null)
 const run=async()=>{setBusy(true);setResult(null);try{const r=await fetch('/api/research/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,mode,maxResults:10})});setResult(await r.json())}catch(e){setResult({ok:false,error:String(e)})}finally{setBusy(false)}}
 return <div className="phase2-shell"><div className="phase2-top"><div><div className="eyebrow">VENTUREOS / RESEARCH LAB</div><h1>Research the market on demand.</h1><p>Provider-mesh execution with normalized evidence and persistence.</p></div></div>
 <div className="p2-research-grid"><div className="p2-card p2-form"><label>Research question</label><textarea value={query} onChange={(e:any)=>setQuery(e.target.value)}/><div className="p2-mode"><span>Mode</span>{(['normal','deep','max'] as const).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div><button className="p2-primary" disabled={busy||!query.trim()} onClick={run}>{busy?<><RefreshCw size={14} className="spin"/> Running provider mesh…</>:<><FlaskConical size={14}/> Run research</>}</button><div className="p2-note"><Zap size={12}/> Routing: Tavily discovery → Exa semantic depth → Firecrawl extraction for MAX.</div></div>
 <div className="p2-card p2-results"><div className="p2-results-head"><div><b>Run result</b><span>Normalized source objects</span></div><Search size={16}/></div>{!result?<div className="p2-empty"><Search size={20}/><b>No research run yet</b><span>Submit a question to test the ingestion layer.</span></div>:result.ok?<div>{result.run.error&&<div className="p2-error"><AlertTriangle size={14}/>{result.run.error}</div>}<div className="p2-banner"><span className={'p2-status '+result.run.status}>{result.run.status}</span><span>{result.run.sources.length} sources</span><span>{result.run.providers.join(' · ')||'no provider configured'}</span></div>{result.run.sources.map((s:any,i:number)=><article className="p2-source-result" key={i}><div><span>{s.provider}</span><a href={s.url} target="_blank" rel="noreferrer">{s.title||s.url}</a><ExternalLink size={11}/></div><p>{s.snippet||s.content?.slice(0,600)||'No snippet returned.'}</p></article>)}</div>:<div className="p2-error-box"><AlertTriangle size={20}/><b>{result.error||'Research failed'}</b><span>Configure provider keys on the server and retry.</span></div>}</div></div>
 </div>
}