'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,ArrowUpRight,Crosshair,RefreshCw,Search,Target,TrendingUp,X,Zap} from 'lucide-react'
export default function Opportunities(){
 const [data,setData]=useState<any>({}),[busy,setBusy]=useState(true),[processing,setProcessing]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<any>(null)
 const load=async()=>{setBusy(true);try{const r=await fetch('/api/opportunities?limit=100',{cache:'no-store'});setData(await r.json())}catch(e){setData({ok:false,error:String(e)})}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const process=async()=>{setProcessing(true);try{const r=await fetch('/api/opportunities/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:100})});const j=await r.json();setData((x:any)=>({...x,process:j.result||j}));await load()}finally{setProcessing(false)}}
 const opportunities=useMemo(()=>((data.opportunities||[]) as any[]).filter(o=>(filter==='all'||(filter==='priority'?o.status==='priority':filter==='candidate'?o.status==='candidate':o.status==='needs_founder_fit'))&&(!query||String(o.title).toLowerCase().includes(query.toLowerCase())||String(o.target_audience||'').toLowerCase().includes(query.toLowerCase())||String(o.industry||'').toLowerCase().includes(query.toLowerCase()))),[data,query,filter])
 const high=opportunities.filter(o=>Number(o.overall_score)>=75).length
 return <div className='phase5-shell'>
  <div className='phase5-top'><div><div className='eyebrow'>VENTUREOS / PHASE 5</div><h1>Opportunity Radar</h1><p>Convert problems, market movement, competition and evidence into buildable opportunity hypotheses.</p></div><div className='phase5-actions'><button className='p5-btn' onClick={load}><RefreshCw size={14}/> Refresh</button><button className='p5-primary' disabled={processing} onClick={process}>{processing?<><RefreshCw className='spin' size={14}/> Building opportunities…</>:<><Zap size={14}/> Generate opportunity radar</>}</button></div></div>
  <section className='p5-kpis'><div><span>OPPORTUNITIES</span><b>{opportunities.length}</b><small>evidence-linked hypotheses</small></div><div><span>HIGH PRIORITY</span><b>{high}</b><small>overall score ≥ 75</small></div><div><span>FOUNDER FIT</span><b>{opportunities.filter(o=>o.founder_fit_score!=null).length}</b><small>configured opportunities</small></div><div><span>AVG EVIDENCE</span><b>{opportunities.length?Math.round(opportunities.reduce((a,o)=>a+Number(o.evidence_quality_score||0),0)/opportunities.length):0}</b><small>quality score / 100</small></div></section>
  {!data.configured&&<div className='p5-alert'><AlertTriangle size={15}/><div><b>Opportunity Radar is in configuration mode.</b><span>{data.message||'Connect the server-side Supabase credentials to load Phase 3/4 intelligence.'}</span></div></div>}
  <section className='p5-radar-grid'><div className='p5-panel'><div className='p5-head'><div><b>2D intelligence map</b><span>Higher demand ↑ · higher monetization →</span></div><div className='p5-filters'>{['all','priority','candidate','needs_founder_fit'].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x.replaceAll('_',' ')}</button>)}</div></div><div className='p5-radar-wrap'><div className='p5-axis-y'><span>HIGH DEMAND</span><span>LOW DEMAND</span></div><div className='p5-radar'><div className='p5-quadrant q1'/><div className='p5-quadrant q2'/><div className='p5-quadrant q3'/><div className='p5-quadrant q4'/><div className='p5-gridline h'/><div className='p5-gridline v'/><div className='p5-axis-x left'>LOW MONETIZATION</div><div className='p5-axis-x right'>HIGH MONETIZATION</div>{opportunities.slice(0,60).map((o:any,i:number)=><button key={o.id} className={'p5-point '+(Number(o.overall_score)>=75?'hot':'')} style={{left:Number(o.radar_x||0)+'%',top:(100-Number(o.radar_y||0))+'%'}} title={o.title} onClick={()=>setSelected(o)}><span>{o.title}</span><b>{String(i+1).padStart(2,'0')}</b></button>)}</div></div>{!busy&&!opportunities.length&&<div className='p5-empty'><Crosshair size={22}/><b>No opportunities yet</b><span>Run Opportunity Radar after Phase 3 problems and Phase 4 evidence are available.</span></div>}</div>
   <aside className='p5-side'><div className='p5-panel p5-ranked'><div className='p5-head'><div><b>Ranked opportunities</b><span>Scored by evidence, demand and fit signals</span></div><Target size={15}/></div><div className='p5-list'>{opportunities.slice(0,12).map((o:any,i:number)=><button key={o.id} onClick={()=>setSelected(o)}><div className='p5-rank'>{String(i+1).padStart(2,'0')}</div><div className='p5-card-main'><div className='p5-card-title'><b>{o.title}</b><span>{o.status}</span></div><p>{o.summary}</p><div className='p5-score-row'><span>Demand <strong>{o.demand_score}</strong></span><span>Evidence <strong>{o.evidence_quality_score}</strong></span><span>Momentum <strong>{o.momentum_score}</strong></span><span>Overall <strong>{o.overall_score}</strong></span></div></div><ArrowUpRight size={14}/></button>)}</div></div>
    <div className='p5-panel p5-why'><div className='p5-head'><div><b>Opportunity contract</b><span>What every generated opportunity must answer</span></div></div><div className='p5-contract'><div><i>01</i><span>Problem</span></div><div><i>02</i><span>Target users</span></div><div><i>03</i><span>Why now</span></div><div><i>04</i><span>Evidence</span></div><div><i>05</i><span>Competition</span></div><div><i>06</i><span>Market gap</span></div><div><i>07</i><span>Business model</span></div><div><i>08</i><span>Founder fit</span></div></div></div></aside></section>
  {selected&&<div className='overlay' onClick={()=>setSelected(null)}><aside className='drawer p5-drawer' onClick={(e:any)=>e.stopPropagation()}><div className='drawerhead'><div><div className='eyebrow'>OPPORTUNITY HYPOTHESIS</div><h2>{selected.title}</h2></div><button className='icon' onClick={()=>setSelected(null)}><X size={15}/></button></div><p className='drawerintro'>{selected.summary}</p><div className='p5-detail-scores'>{[['Demand',selected.demand_score],['Pain',selected.pain_score],['Momentum',selected.momentum_score],['Monetization',selected.monetization_score],['Competition',selected.competition_score],['Distribution Fit',selected.distribution_fit_score],['Build Complexity',selected.build_complexity_score],['Evidence Quality',selected.evidence_quality_score]].map((x:any)=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><i><em style={{width:String(x[1])+'%'}}/></i></div>)}</div><div className='p5-detail-block'><label>WHY NOW</label><p>{selected.why_now}</p></div><div className='p5-detail-block'><label>COMPETITIVE GAP</label><p>{selected.market_gap}</p></div><div className='p5-detail-block'><label>BUSINESS MODEL</label><p>{selected.business_model}</p></div><div className='p5-detail-block'><label>FOUNDER FIT</label><p>{selected.founder_fit_score==null?'Not configured yet — Founder Memory is the Phase 6 source of truth.':selected.founder_fit_score+'/100'}</p></div><button className='p5-primary wide' onClick={()=>window.location.href='/opportunities/'+selected.id}><TrendingUp size={14}/> Open opportunity detail</button></aside></div>}
 </div>
}