'use client'
import {useEffect,useState} from 'react'
import {AlertTriangle,ArrowLeft,ExternalLink,RefreshCw,Target,TrendingUp} from 'lucide-react'
export default function OpportunityDetail({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''),[data,setData]=useState<any>({}),[busy,setBusy]=useState(true)
 useEffect(()=>{params.then(x=>setId(x.id))},[params])
 useEffect(()=>{if(!id)return;setBusy(true);fetch('/api/opportunities?id='+id,{cache:'no-store'}).then(r=>r.json()).then(setData).catch(e=>setData({ok:false,error:String(e)})).finally(()=>setBusy(false))},[id])
 if(busy)return <div className='phase5-shell'><div className='p5-empty detail-loading'><RefreshCw className='spin' size={20}/><b>Loading opportunity intelligence…</b></div></div>
 const o=data.opportunity
 if(!data.ok||!o)return <div className='phase5-shell'><div className='p5-alert'><AlertTriangle size={15}/><div><b>{data.error||'Opportunity not found'}</b><span>Open the Opportunity Radar and select a generated opportunity.</span></div></div></div>
 const score=(name:string)=>data.scores?.find((s:any)=>s.dimension===name)
 return <div className='phase5-shell'><div className='p5-detail-top'><button className='p5-btn' onClick={()=>window.location.href='/opportunities'}><ArrowLeft size={14}/> Opportunity Radar</button><span className='p5-detail-status'>{o.status}</span></div><section className='p5-detail-hero'><div><div className='eyebrow'>OPPORTUNITY #{String(o.id).padStart(3,'0')}</div><h1>{o.title}</h1><p>{o.summary}</p><div className='p5-detail-tags'><span>{o.industry||'General'}</span><span>{o.target_audience||'Audience pending'}</span><span>{o.business_model||'Business model pending'}</span></div></div><div className='p5-overall'><small>OVERALL</small><strong>{o.overall_score}</strong><span>{o.confidence}% confidence</span></div></section>
 <section className='p5-detail-grid'><div className='p5-detail-main'>
  <div className='p5-panel'><div className='p5-head'><div><b>Opportunity thesis</b><span>Problem → market → money → timing → distribution → founder fit</span></div><Target size={15}/></div><div className='p5-thesis'><article><label>PROBLEM</label><p>{o.summary}</p></article><article><label>WHY NOW</label><p>{o.why_now}</p></article><article><label>MARKET GAP</label><p>{o.market_gap}</p></article><article><label>BUSINESS MODEL</label><p>{o.business_model}</p></article></div></div>
  <div className='p5-panel'><div className='p5-head'><div><b>Scoring breakdown</b><span>Every score has a stored rationale</span></div><TrendingUp size={15}/></div><div className='p5-score-detail'>{[['demand','Demand'],['pain','Pain'],['momentum','Momentum'],['monetization','Willingness to Pay'],['competition','Competition'],['distribution_fit','Distribution Fit'],['build_complexity','Build Complexity'],['evidence_quality','Evidence Quality'],['founder_fit','Founder Fit']].map(([key,label])=>{const s=score(key);return <div key={key}><div><span>{label}</span><b>{key==='founder_fit'&&o.founder_fit_score==null?'—':s?.score??0}</b></div><p>{s?.rationale||'No score rationale available.'}</p><i><em style={{width:String(Math.max(0,Math.min(100,Number(s?.score||0))))+'%'}}/></i></div>})}</div></div>
  <div className='p5-panel'><div className='p5-head'><div><b>Evidence</b><span>{o.evidence_count} linked records · {o.source_count} source domains</span></div><ExternalLink size={15}/></div><div className='p5-op-evidence'>{(data.evidence||[]).map((row:any)=><article key={row.evidence?.id||row.evidence_id}><div><span>{row.evidence?.evidence_status||'context'}</span><span>{row.evidence?.source_type||'web'}</span><strong>{row.evidence?.evidence_score||0}</strong></div><b>{row.evidence?.claim_text||'Evidence record'}</b><p>{row.evidence?.snippet||'No snippet available.'}</p>{row.evidence?.source_url&&<a href={row.evidence.source_url} target='_blank' rel='noreferrer'>{row.evidence.source_domain} ↗</a>}</article>)}</div></div>
 </div><aside className='p5-detail-side'><div className='p5-panel'><div className='p5-head'><div><b>Radar position</b><span>Demand × monetization</span></div></div><div className='p5-mini-radar'><div className='mini-cross h'/><div className='mini-cross v'/><div className='mini-point' style={{left:o.radar_x+'%',top:(100-o.radar_y)+'%'}}/><span>LOW MONETIZATION</span><span>HIGH MONETIZATION</span><em>HIGH DEMAND</em><i>LOW DEMAND</i></div></div><div className='p5-panel'><div className='p5-head'><div><b>Validation gates</b><span>What still needs proof</span></div></div><div className='p5-gates'><div><span>Evidence quality</span><b>{o.evidence_quality_score>=75?'PASS':'NEEDS MORE'}</b></div><div><span>Competitive gap</span><b>{o.competition_score>=55?'OPEN':'CROWDED'}</b></div><div><span>Distribution fit</span><b>{o.distribution_fit_score>=70?'STRONG':'VALIDATE'}</b></div><div><span>Founder fit</span><b>{o.founder_fit_score==null?'PHASE 6':'CONFIGURED'}</b></div></div></div></aside></section></div>
}