'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,CheckCircle2,ChevronRight,Database,Filter,RefreshCw,Search,X} from 'lucide-react'
export default function Evidence(){
 const [data,setData]=useState<any>({}),[busy,setBusy]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<any>(null)
 const load=async()=>{setBusy(true);try{const r=await fetch('/api/evidence?limit=200',{cache:'no-store'});setData(await r.json())}catch(e){setData({ok:false,error:String(e)})}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const rows=useMemo(()=>((data.evidence||[]) as any[]).filter(e=>(status==='all'||e.evidence_status===status)&&(!query||String(e.claim_text).toLowerCase().includes(query.toLowerCase())||String(e.source_domain).toLowerCase().includes(query.toLowerCase()))),[data,query,status])
 const counts=useMemo(()=>{const r=data.evidence||[];return {observed:r.filter((x:any)=>x.evidence_status==='observed').length,contradictory:r.filter((x:any)=>x.evidence_status==='contradictory').length,unverified:r.filter((x:any)=>x.evidence_status==='unverified').length}},[data])
 return <div className='phase4-shell'>
 <div className='phase4-top'><div><div className='eyebrow'>VENTUREOS / EVIDENCE EXPLORER</div><h1>Evidence Explorer</h1><p>Every market conclusion is traceable to a source, claim and confidence score.</p></div><button className='p4-btn' onClick={load}><RefreshCw size={14}/> Refresh</button></div>
 <section className='p4-evidence-kpis'><div><span>RANKED EVIDENCE</span><b>{rows.length}</b></div><div><span>OBSERVED</span><b>{counts.observed}</b></div><div><span>CONTRADICTORY</span><b>{counts.contradictory}</b></div><div><span>UNVERIFIED</span><b>{counts.unverified}</b></div></section>
 {!data.configured&&<div className='p4-alert'><AlertTriangle size={15}/><div><b>Evidence Explorer is ready but not connected to live data.</b><span>{data.message||'Connect Supabase server credentials.'}</span></div></div>}
 <div className='p4-panel p4-evidence-page'><div className='p4-evidence-toolbar'><div className='p4-search'><Search size={14}/><input value={query} onChange={(e:any)=>setQuery(e.target.value)} placeholder='Search claim, domain or entity…'/></div><div className='p4-filters'>{['all','observed','contradictory','unverified'].map(x=><button className={status===x?'active':''} onClick={()=>setStatus(x)} key={x}><Filter size={10}/>{x}</button>)}</div></div>{busy?<div className='p4-empty'><RefreshCw className='spin' size={18}/><b>Loading evidence graph…</b></div>:rows.length===0?<div className='p4-empty'><Database size={22}/><b>No evidence records yet</b><span>Run Phase 4 processing after Phase 2/3 data is available.</span></div>:<div className='p4-evidence-list'>{rows.map((e:any)=><button className='p4-evidence-row' key={e.id} onClick={()=>setSelected(e)}><div className='p4-ev-icon'>{e.evidence_status==='observed'?<CheckCircle2 size={14}/>:e.evidence_status==='contradictory'?<AlertTriangle size={14}/>:<ChevronRight size={14}/>}</div><div className='p4-ev-main'><div><span>{e.evidence_status}</span><span>{e.source_type}</span><span>{e.stance}</span></div><b>{e.claim_text}</b><p>{e.snippet||'No source snippet available.'}</p><small>{e.source_domain} · {e.entity_domain||'unresolved'} · {e.published_at?new Date(e.published_at).toLocaleDateString('en-IN'):'date unavailable'}</small></div><div className='p4-ev-score'><strong>{e.evidence_score}</strong><span>/100</span><small>confidence {Math.round(Number(e.source_confidence)*100)}%</small></div></button>)}</div>}</div>
 {selected&&<div className='overlay' onClick={()=>setSelected(null)}><aside className='drawer p4-drawer' onClick={(e:any)=>e.stopPropagation()}><div className='drawerhead'><div><div className='eyebrow'>EVIDENCE RECORD</div><h2>{selected.claim_text}</h2></div><button className='icon' onClick={()=>setSelected(null)}><X size={15}/></button></div><p className='drawerintro'>{selected.snippet||'No snippet available.'}</p><div className='p3-detail-grid'><div><span>Evidence score</span><b>{selected.evidence_score}/100</b></div><div><span>Source confidence</span><b>{Math.round(Number(selected.source_confidence)*100)}%</b></div><div><span>Stance</span><b>{selected.stance}</b></div><div><span>Status</span><b>{selected.evidence_status}</b></div></div><div className='p3-detail-section'><label>Source</label><a className='p4-source-link' href={selected.source_url} target='_blank' rel='noreferrer'>{selected.source_domain} ↗</a></div><div className='p3-detail-section'><label>Classification</label><div><span>{selected.source_type}</span><span>{selected.entity_domain||'Unresolved entity'}</span></div></div></aside></div>}
 </div>
}
