'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,BarChart3,BrainCircuit,CheckCircle2,CircleDollarSign,CloudCog,Database,Gauge,History,Loader2,RefreshCw,Save,ShieldAlert,Sparkles,WalletCards,Zap} from 'lucide-react'

const providerMeta:any={openai:['AI','OpenAI'],tavily:['Search','Tavily'],firecrawl:['Scraping','Firecrawl'],exa:['Research','Exa'],infra:['Infrastructure','Infrastructure']}
const categoryLabel:any={ai:'AI / Reasoning',search:'Web Search',scraping:'Scraping',research:'Research',infrastructure:'Infrastructure'}
function money(v:any){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}
function pct(v:any){return Number(v||0).toFixed(1)+'%'}
function stateTone(s:string){return s==='healthy'?'healthy':s==='alert'?'alert':s==='warning'?'warning':s==='soft_stop'||s==='hard_stop'?'danger':'muted'}
export default function CostOS(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[reconciling,setReconciling]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const [budget,setBudget]=useState({monthly_limit:'',daily_limit:'',alert_percent:'75',warning_percent:'85',soft_stop_percent:'90',hard_stop_percent:'100'})
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/cost/summary',{cache:'no-store'}),j=await r.json();if(!j.ok)throw new Error(j.error||'Cost OS unavailable');setData(j);const a=j.account;if(a)setBudget({monthly_limit:a.monthly_limit?String(a.monthly_limit):'',daily_limit:a.daily_limit?String(a.daily_limit):'',alert_percent:String(a.alert_percent??75),warning_percent:String(a.warning_percent??85),soft_stop_percent:String(a.soft_stop_percent??90),hard_stop_percent:String(a.hard_stop_percent??100)})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const saveBudget=async()=>{setSaving(true);setMessage('');setError('');try{const r=await fetch('/api/cost/budget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({monthly_limit:Number(budget.monthly_limit||0),daily_limit:Number(budget.daily_limit||0),alert_percent:Number(budget.alert_percent),warning_percent:Number(budget.warning_percent),soft_stop_percent:Number(budget.soft_stop_percent),hard_stop_percent:Number(budget.hard_stop_percent)})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Budget update failed');setMessage('Budget and guardrails saved.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}}
 const reconcile=async()=>{setReconciling(true);setMessage('');try{const r=await fetch('/api/cost/reconcile',{method:'POST'}),j=await r.json();if(!j.ok)throw new Error(j.error||'Reconciliation failed');setMessage('Cost ledger reconciled just now.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setReconciling(false)}}
 const s=data?.summary||{},a=data?.account||{},providers=data?.providers||[],accounts=data?.providerAccounts||[],tx=data?.transactions||[]
 const budgetConfigured=Number(a.monthly_limit||0)>0
 const cats=data?.categories||{},providerSpend=data?.providerSpend||{},oppSpend=data?.opportunitySpend||{},prodSpend=data?.productSpend||{}
 const topProviders=useMemo(()=>Object.entries(providerSpend).sort((a:any,b:any)=>Number(b[1])-Number(a[1])),[providerSpend])
 return <main className="p9-shell">
  <header className="p9-top"><div><div className="p9-eyebrow">VENTUREOS / PHASE 9 / COST OS</div><h1>Cost Control Center</h1><p>One internal cost ledger for intelligence consumption. User billing stays abstracted from provider spend; providers remain VentureOS infrastructure.</p></div><div className="p9-actions"><button className="p9-btn" onClick={load}><RefreshCw size={14}/> Refresh</button><button className="p9-btn primary" onClick={reconcile} disabled={reconciling}>{reconciling?<><RefreshCw size={13} className="p9-spin"/> Reconciling…</>:<><Zap size={13}/> Reconcile costs</>}</button></div></header>
  {error&&<div className="p9-banner danger"><AlertTriangle size={15}/><div><b>Cost OS error</b><span>{error}</span></div></div>}
  {!loading&&data&&!budgetConfigured&&<div className="p9-banner info"><WalletCards size={15}/><div><b>No VentureOS intelligence budget is active.</b><span>Set an internal monthly intelligence budget below. This does not create a payment wallet; it establishes consumption limits and provider-spend guardrails.</span></div></div>}
  {message&&<div className="p9-banner success"><CheckCircle2 size={15}/><div><b>{message}</b></div></div>}
  {loading?<div className="p9-panel p9-empty"><Loader2 className="p9-spin" size={24}/><strong>Loading Cost OS…</strong><span>Reading budgets, provider usage and internal ledger transactions.</span></div>:
   <>{<section className="p9-hero-grid">
    <div className="p9-panel p9-budget-hero"><div className="p9-section-head"><div><b>Monthly intelligence budget</b><span>Internal VentureOS consumption allowance.</span></div><Gauge size={16}/></div><div className="p9-budget-main"><div><small>CONSUMED</small><strong>{money(s.consumed)}</strong><span>of {money(s.monthlyBudget)}</span></div><div className={'p9-health '+stateTone(s.state)}><small>CONTROL STATE</small><b>{s.state==='unconfigured'?'NOT CONFIGURED':s.state.replace('_',' ').toUpperCase()}</b><span>{pct(s.percent)} of budget</span></div></div><div className="p9-budget-bar"><i style={{width:Math.min(100,Number(s.percent||0))+'%'}}/></div><div className="p9-budget-stats"><div><span>Reserved</span><b>{money(s.reserved)}</b></div><div><span>Available</span><b>{money(s.available)}</b></div><div><span>Forecast</span><b>{money(s.forecast)}</b></div><div><span>Daily avg</span><b>{money(s.dailyAverage)}</b></div></div></div>
    <div className="p9-panel p9-billing"><div className="p9-section-head"><div><b>Unified billing</b><span>One VentureOS subscription surface.</span></div><CloudCog size={16}/></div><div className="p9-billing-main"><div className="p9-billing-logo"><CircleDollarSign size={20}/></div><div><b>{data.subscription?.plan_id||'Founder plan'}</b><span>{data.subscription?.status||'unconfigured'}</span></div></div><div className="p9-billing-row"><span>Customer payment gateway</span><b>{data.subscription?.payment_provider||'Not connected'}</b></div><div className="p9-billing-row"><span>Gateway readiness</span><b className={data.subscription?.payment_provider?'good':''}>{data.subscription?.payment_provider?'Ready':'Configuration required'}</b></div><div className="p9-mini-note"><ShieldAlert size={12}/><span>Provider API keys remain server-side. Cost OS never exposes vendor secrets to the founder UI.</span></div></div>
   </section>
   <section className="p9-kpis"><div><span>API efficiency</span><b>{Number(s.efficiency||0).toFixed(2)}</b><small>tracked units / ₹</small></div><div><span>Provider spend</span><b>{money(Object.values(providerSpend).reduce((n:any,v:any)=>n+Number(v||0),0))}</b><small>current month</small></div><div><span>Opportunities with cost</span><b>{Object.keys(oppSpend).length}</b><small>tracked intelligence</small></div><div><span>Products with cost</span><b>{Object.keys(prodSpend).length}</b><small>tracked build spend</small></div></section>
   <section className="p9-grid">
    <div className="p9-panel"><div className="p9-section-head"><div><b>Spend by category</b><span>Where VentureOS intelligence budget is going.</span></div><BarChart3 size={15}/></div><div className="p9-bars">{Object.keys(categoryLabel).map((k)=>{const v=Number(cats[k]||0),max=Math.max(...Object.values(cats).map((x:any)=>Number(x||0)),1);return <div className="p9-bar-row" key={k}><div><span>{categoryLabel[k]}</span><b>{money(v)}</b></div><i><em style={{width:Math.min(100,v/max*100)+'%'}}/></i></div>})}</div></div>
    <div className="p9-panel"><div className="p9-section-head"><div><b>Provider ledger</b><span>Internal COGS accounting by provider.</span></div><Database size={15}/></div><div className="p9-provider-list">{providers.map((p:any)=>{const spend=Number(providerSpend[p.provider_key]||0),ready=accounts.find((x:any)=>x.provider_id===p.id)?.secret_configured;return <div className="p9-provider" key={p.provider_key}><div className="p9-provider-icon">{providerMeta[p.provider_key]?.[0]?.[0]||'P'}</div><div><b>{p.display_name}</b><span>{categoryLabel[p.category]||p.category} · {ready?'connected':'not configured'}</span></div><strong>{money(spend)}</strong></div>})}</div></div>
   </section>
   <section className="p9-grid">
    <div className="p9-panel"><div className="p9-section-head"><div><b>Cost per opportunity</b><span>Intelligence economics at the opportunity layer.</span></div><TargetIcon/></div><div className="p9-simple-list">{Object.entries(oppSpend).sort((a:any,b:any)=>Number(b[1])-Number(a[1])).slice(0,12).map(([id,v]:any)=><div key={id}><span>Opportunity #{id}</span><b>{money(v)}</b></div>)}</div>{!Object.keys(oppSpend).length&&<div className="p9-empty compact"><strong>No opportunity-level cost recorded</strong><span>Provider usage must be tagged with an opportunity_id.</span></div>}</div>
    <div className="p9-panel"><div className="p9-section-head"><div><b>Cost per product</b><span>Build and intelligence cost by product.</span></div><WorkflowIcon/></div><div className="p9-simple-list">{Object.entries(prodSpend).sort((a:any,b:any)=>Number(b[1])-Number(a[1])).slice(0,12).map(([id,v]:any)=><div key={id}><span>Product #{id}</span><b>{money(v)}</b></div>)}</div>{!Object.keys(prodSpend).length&&<div className="p9-empty compact"><strong>No product-level cost recorded</strong><span>Provider usage must be tagged with a product_id.</span></div>}</div>
   </section>
   <section className="p9-grid">
    <div className="p9-panel"><div className="p9-section-head"><div><b>Budget guardrails</b><span>Hard stops prevent uncontrolled provider spend.</span></div><ShieldAlert size={15}/></div><div className="p9-guardrails"><div><span>Alert</span><b>{a.alert_percent||75}%</b></div><div><span>Warning</span><b>{a.warning_percent||85}%</b></div><div><span>Soft stop</span><b>{a.soft_stop_percent||90}%</b></div><div><span>Hard stop</span><b>{a.hard_stop_percent||100}%</b></div></div><div className="p9-autostop"><CheckCircle2 size={13}/><span>Reservation RPC enforces the hard-stop boundary before provider work is allowed to proceed.</span></div></div>
    <div className="p9-panel"><div className="p9-section-head"><div><b>Budget configuration</b><span>Set monthly and daily intelligence limits.</span></div><Save size={15}/></div><div className="p9-form"><label>Monthly budget<input type="number" value={budget.monthly_limit} onChange={(e:any)=>setBudget({...budget,monthly_limit:e.target.value})} placeholder="10000"/></label><label>Daily limit<input type="number" value={budget.daily_limit} onChange={(e:any)=>setBudget({...budget,daily_limit:e.target.value})} placeholder="1000"/></label><label>Alert %<input type="number" value={budget.alert_percent} onChange={(e:any)=>setBudget({...budget,alert_percent:e.target.value})}/></label><label>Warning %<input type="number" value={budget.warning_percent} onChange={(e:any)=>setBudget({...budget,warning_percent:e.target.value})}/></label><label>Soft stop %<input type="number" value={budget.soft_stop_percent} onChange={(e:any)=>setBudget({...budget,soft_stop_percent:e.target.value})}/></label><label>Hard stop %<input type="number" value={budget.hard_stop_percent} onChange={(e:any)=>setBudget({...budget,hard_stop_percent:e.target.value})}/></label><button className="p9-primary" onClick={saveBudget} disabled={saving}>{saving?<><RefreshCw size={12} className="p9-spin"/> Saving…</>:<><Save size={12}/> Save guardrails</>}</button></div></div>
   </section>
   <section className="p9-panel"><div className="p9-section-head"><div><b>Recent ledger</b><span>Grant → reserve → consume → release audit trail.</span></div><History size={15}/></div>{tx.length?<div className="p9-table">{tx.slice(0,18).map((x:any)=><div key={x.id}><span>{new Date(x.created_at).toLocaleString()}</span><b className={'tx '+String(x.type).toLowerCase()}>{x.type}</b><span>{x.reason||'—'}</span><strong>{money(x.amount)}</strong></div>)}</div>:<div className="p9-empty compact"><History size={18}/><strong>No cost transactions yet</strong><span>Billing grants and provider consumption will appear here.</span></div>}</section>
   <footer className="p9-footer"><span>VentureOS Phase 9 · Cost OS + Unified Billing</span><span>Internal credits are consumption rights, not a general-purpose money wallet.</span></footer>
  </>}
 </main>
}
function TargetIcon(){return <Sparkles size={15}/>}function WorkflowIcon(){return <CloudCog size={15}/>}
