import { ventureosConfigured, ventureosRequest } from '@/lib/tenant/rest'
const request = ventureosRequest
export async function opportunityClusters(limit=200){return request('ventureos_problem_clusters?select=*&status=neq.archived&order=momentum_score.desc&limit='+Math.min(limit,300))}
export async function clusterMembers(clusterId:number,limit=100){return request('ventureos_problem_cluster_members?select=signal_id,similarity&cluster_id=eq.'+clusterId+'&order=similarity.desc&limit='+Math.min(limit,150))}
export async function allClusterMembers(limit=5000){return request('ventureos_problem_cluster_members?select=cluster_id,signal_id,similarity&order=assigned_at.desc&limit='+Math.min(limit,10000))}
export async function marketEvents(limit=200){return request('ventureos_market_events?select=*&order=detected_at.desc&limit='+Math.min(limit,300))}
export async function competitors(limit=200){return request('ventureos_competitor_snapshots?select=*&order=change_score.desc,snapshot_at.desc&limit='+Math.min(limit,300))}
export async function evidenceRows(limit=2000){return request('ventureos_evidence?select=*&order=evidence_score.desc&limit='+Math.min(limit,2000))}
export async function upsertOpportunity(row:Record<string,unknown>){const q=await request('ventureos_opportunities?select=*&opportunity_key=eq.'+encodeURIComponent(String(row.opportunity_key))+'&limit=1');if(q?.[0]){const [r]=await request('ventureos_opportunities?id=eq.'+q[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return r}return (await request('ventureos_opportunities',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function upsertScore(row:Record<string,unknown>){const q=await request('ventureos_opportunity_scores?select=*&opportunity_id=eq.'+row.opportunity_id+'&dimension=eq.'+encodeURIComponent(String(row.dimension))+'&limit=1');if(q?.[0]){const [r]=await request('ventureos_opportunity_scores?id=eq.'+q[0].id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return r}return (await request('ventureos_opportunity_scores',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]}
export async function linkEvidence(row:Record<string,unknown>){await request('ventureos_opportunity_evidence',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(row)})}
export async function createRun(id:string){return (await request('ventureos_opportunity_processing_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({run_id:id,status:'running'})}))[0]}
export async function finishRun(id:string,patch:Record<string,unknown>){await request('ventureos_opportunity_processing_runs?run_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...patch,status:patch.error?'partial':'completed',completed_at:new Date().toISOString()})})}
export async function opportunities(limit=100){return request('ventureos_opportunities?select=*&order=overall_score.desc&limit='+Math.min(limit,200))}
export async function opportunityById(id:number){const rows=await request('ventureos_opportunities?select=*&id=eq.'+id+'&limit=1');return rows?.[0]??null}
export async function opportunityScores(id:number){return request('ventureos_opportunity_scores?select=*&opportunity_id=eq.'+id+'&order=score.desc')}
export async function opportunityEvidence(id:number){return request('ventureos_opportunity_evidence?select=weight,relation,evidence:ventureos_evidence(*)&opportunity_id=eq.'+id+'&order=weight.desc&limit=100')}
export async function runHistory(limit=20){return request('ventureos_opportunity_processing_runs?select=*&order=started_at.desc&limit='+Math.min(limit,50))}
